### ISSUE TITLE
CMake 3.10.0 automoc generates files in a different directory

### ISSUE THREAD

**Issue by markasselin** [PlusToolkit/PlusLib#283] opened 2017-12-06 20:39 UTC
From the CMake 3.10.0 release notes:
"When using AUTOMOC or AUTOUIC with a multi configuration generator (e.g. Xcode), included *.moc, moc_*.cpp and ui_*.h files are generated in <AUTOGEN_BUILD_DIR>/include_<CONFIG> instead of <AUTOGEN_BUILD_DIR>/include."

@lassoan this was an intentional change.

**Comment by lassoan** [comment] 2017-12-06 21:26
Could we add both .../include and  .../include_ to the list of include directories?

**Comment by markasselin** [comment] 2017-12-07 02:11
Unfortunately not - this leaves non-existent directories in the INTERFACE_INCLUDE_DIRECTORIES. I have a working solution which wraps the addition of .../include, .../include_Debug and .../include_Release in if statements checking if the directory exists - but there must be a cleaner solution than this...

**Comment by lassoan** [comment] 2017-12-07 02:24
It is possible that these include directories are set as target properties in some targets. If we link that target then the appropriate include directory is added automatically. Could you check if build succeeds if we simply remove the manual directory include?

**Comment by markasselin** [comment] 2017-12-07 02:55
No luck, build fails without the manual directory include.

**Comment by lassoan** [comment] 2017-12-08 16:53
Nice work! Don't forget to close this issue if the problem is resolved.

**Comment by markasselin** [comment] 2017-12-10 17:38
@lassoan Just a reminder to merge [PR 284](https://github.com/PlusToolkit/PlusLib/pull/284)

**Comment by lassoan** [comment] 2017-12-10 18:12
Thank you!

**Closed by lassoan** 2017-12-10 18:12 UTC
