### ISSUE TITLE
Build failure in release mode in Visual Studio 2017

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#269] opened 2017-11-10 20:13 UTC
The most recent version fails to build on 64-bit VS2017 in release mode. Debug mode builds fine. Errors are unresolved externals. The first error message is below:

vtkPlusServerTest.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl PlusTransformName::PlusTransformName(class PlusTransformName const &)" (__imp_??0PlusTransformName@@QEAA@AEBV0@@Z) referenced in function "enum PlusStatus __cdecl ConnectClients(int,class std::vector<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource>,class std::allocator<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource> > > &,int,class vtkSmartPointer<class vtkXMLDataElement>)" (?ConnectClients@@YA?AW4PlusStatus@@HAEAV?$vector@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@V?$allocator@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@@std@@@std@@HV?$vtkSmartPointer@VvtkXMLDataElement@@@@@Z) [C:\Dev\PlusGit\b64-17\PlusLib-bin\src\PlusServer\Testing\vtkPlusServerTest.vcxproj]

**Comment by lassoan** [comment] 2017-11-13 01:55
What CMake version do you use?
Try force rebuild of vtkPlusCommon. 
If that does not solve the issue, rebuild everything from scratch, in a much shorter directory path (for example, c:\D\P).

**Comment by adamrankin** [comment] 2017-11-13 15:16
Which devices enabled?

**Comment by dzenanz** [comment] 2017-11-13 15:57
Only MMF video and WinProbe video non-default devices. Static libraries. I am making a clean build in `C:\_\PL17`

**Comment by dzenanz** [comment] 2017-11-13 17:24
The error is still there. The complete build log is attached.
[buildLog.txt](https://github.com/PlusToolkit/PlusLib/files/1467772/buildLog.txt)

**Comment by dzenanz** [comment] 2017-11-13 17:27
Here is the CMakeCache.txt of the super-build:
[CMakeCache.txt](https://github.com/PlusToolkit/PlusLib/files/1467785/CMakeCache.txt)

**Comment by dzenanz** [comment] 2017-11-13 17:30
I was using CMake 3.9.6] for this.

**Comment by lassoan** [comment] 2017-11-13 17:48
Do you build with static libraries or DLLs?

**Comment by dzenanz** [comment] 2017-11-13 18:20
Static libraries.

**Comment by lassoan** [comment] 2017-11-13 18:51
I could reproduce the problem (only the warning LNK4217: locally defined symbol; not the errors). The problem is that only PlusLib was set to static build and not PlusApp. A mixed model should be possible but it would require tuning of how BUILD_SHARED_LIBS is handled in PlusLib.

**Comment by lassoan** [comment] 2017-11-13 19:00
Fix of setting static build in both PlusApp and PlusLib: https://github.com/PlusToolkit/PlusBuild/commit/ea7e57f1eb8de3dd48913311fd11134032bdc70e

I haven't tested if it fixes the error in itself. PlusConfigure.h file defines PlusLib_STATIC, so it may be possible that even though BUILD_SHARED_LIBS is specified, PlusLib_STATIC is still not.

@dzenanz It would be great if you could test if setting static build for PlusApp fixes the problem and if not then investigate it a bit further. If you don't have time or stuck then let us know and @Sunderlandkyl should be able to have a look.

**Comment by dzenanz** [comment] 2017-11-13 19:36
This did not seem to help. Moreover, the first error is in PlusLib. Here is a log of a repeated build:

```
1>------ Build started: Project: PlusWidgets_autogen, Configuration: Release x64 ------
2>------ Build started: Project: vtkPlusServerTest, Configuration: Release x64 ------
1>Automatic MOC, UIC and RCC for target PlusWidgets
3>------ Build started: Project: ToolStateDisplayWidgetTest_autogen, Configuration: Release x64 ------
4>------ Skipped Build: Project: RUN_TESTS, Configuration: Release x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Build: Project: NightlyMemoryCheck, Configuration: Release x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Build: Project: Experimental, Configuration: Release x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Build: Project: Nightly, Configuration: Release x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: Documentation-PlusLib-Editing, Configuration: Release x64 ------
8>Project not selected to build for this solution configuration 
9>------ Skipped Build: Project: Continuous, Configuration: Release x64 ------
9>Project not selected to build for this solution configuration 
3>Automatic MOC, UIC and RCC for target ToolStateDisplayWidgetTest
2>   Creating library C:/_/PL17/lib/Release/vtkPlusServerTest.lib and object C:/_/PL17/lib/Release/vtkPlusServerTest.exp
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?Instance@vtkPlusLogger@@SAPEAV1@XZ (public: static class vtkPlusLogger * __cdecl vtkPlusLogger::Instance(void)) imported in function "enum PlusStatus __cdecl ConnectClients(int,class std::vector<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource>,class std::allocator<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource> > > &,int,class vtkSmartPointer<class vtkXMLDataElement>)" (?ConnectClients@@YA?AW4PlusStatus@@HAEAV?$vector@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@V?$allocator@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@@std@@@std@@HV?$vtkSmartPointer@VvtkXMLDataElement@@@@@Z)
2>vtkPlusRendering.lib(PlusPlotter.obj) : warning LNK4049: locally defined symbol ?Instance@vtkPlusLogger@@SAPEAV1@XZ (public: static class vtkPlusLogger * __cdecl vtkPlusLogger::Instance(void)) imported
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?LogMessage@vtkPlusLogger@@QEAAXW4LogLevelType@1@PEBD1H1@Z (public: void __cdecl vtkPlusLogger::LogMessage(enum vtkPlusLogger::LogLevelType,char const *,char const *,int,char const *)) imported in function "enum PlusStatus __cdecl ConnectClients(int,class std::vector<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource>,class std::allocator<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource> > > &,int,class vtkSmartPointer<class vtkXMLDataElement>)" (?ConnectClients@@YA?AW4PlusStatus@@HAEAV?$vector@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@V?$allocator@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@@std@@@std@@HV?$vtkSmartPointer@VvtkXMLDataElement@@@@@Z)
2>vtkPlusRendering.lib(PlusPlotter.obj) : warning LNK4049: locally defined symbol ?LogMessage@vtkPlusLogger@@QEAAXW4LogLevelType@1@PEBD1H1@Z (public: void __cdecl vtkPlusLogger::LogMessage(enum vtkPlusLogger::LogLevelType,char const *,char const *,int,char const *)) imported
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?GetLogLevel@vtkPlusLogger@@QEAAHXZ (public: int __cdecl vtkPlusLogger::GetLogLevel(void)) imported in function main
2>vtkPlusRendering.lib(PlusPlotter.obj) : warning LNK4049: locally defined symbol ?GetLogLevel@vtkPlusLogger@@QEAAHXZ (public: int __cdecl vtkPlusLogger::GetLogLevel(void)) imported
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?GetLogLevelString@vtkPlusLogger@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ (public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl vtkPlusLogger::GetLogLevelString(void)) imported in function main
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?SetLogLevel@vtkPlusLogger@@QEAAXH@Z (public: void __cdecl vtkPlusLogger::SetLogLevel(int)) imported in function main
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?GetLogFileName@vtkPlusLogger@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ (public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl vtkPlusLogger::GetLogFileName(void)) imported in function main
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?PrintXML@XML@PlusCommon@@YA?AW4PlusStatus@@AEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@VvtkIndent@@PEAVvtkXMLDataElement@@@Z (enum PlusStatus __cdecl PlusCommon::XML::PrintXML(class std::basic_ostream<char,struct std::char_traits<char> > &,class vtkIndent,class vtkXMLDataElement *)) imported in function "class vtkSmartPointer<class vtkPlusOpenIGTLinkServer> __cdecl StartServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?StartServer@@YA?AV?$vtkSmartPointer@VvtkPlusOpenIGTLinkServer@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ??1PlusTransformName@@QEAA@XZ (public: __cdecl PlusTransformName::~PlusTransformName(void)) imported in function "enum PlusStatus __cdecl ConnectClients(int,class std::vector<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource>,class std::allocator<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource> > > &,int,class vtkSmartPointer<class vtkXMLDataElement>)" (?ConnectClients@@YA?AW4PlusStatus@@HAEAV?$vector@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@V?$allocator@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@@std@@@std@@HV?$vtkSmartPointer@VvtkXMLDataElement@@@@@Z)
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ??0PlusTransformName@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z (public: __cdecl PlusTransformName::PlusTransformName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)) imported in function "enum PlusStatus __cdecl ConnectClients(int,class std::vector<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource>,class std::allocator<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource> > > &,int,class vtkSmartPointer<class vtkXMLDataElement>)" (?ConnectClients@@YA?AW4PlusStatus@@HAEAV?$vector@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@V?$allocator@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@@std@@@std@@HV?$vtkSmartPointer@VvtkXMLDataElement@@@@@Z)
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?DelayWithEventProcessing@vtkPlusAccurateTimer@@SAXN@Z (public: static void __cdecl vtkPlusAccurateTimer::DelayWithEventProcessing(double)) imported in function main
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?GetSystemTime@vtkPlusAccurateTimer@@SANXZ (public: static double __cdecl vtkPlusAccurateTimer::GetSystemTime(void)) imported in function main
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?GetInstance@vtkPlusConfig@@SAPEAV1@XZ (public: static class vtkPlusConfig * __cdecl vtkPlusConfig::GetInstance(void)) imported in function "public: static enum PlusStatus __cdecl PlusXmlUtils::ReadDeviceSetConfigurationFromFile(class vtkXMLDataElement *,char const *)" (?ReadDeviceSetConfigurationFromFile@PlusXmlUtils@@SA?AW4PlusStatus@@PEAVvtkXMLDataElement@@PEBD@Z)
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?GetDeviceSetConfigurationPath@vtkPlusConfig@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z (public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl vtkPlusConfig::GetDeviceSetConfigurationPath(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported in function "public: static enum PlusStatus __cdecl PlusXmlUtils::ReadDeviceSetConfigurationFromFile(class vtkXMLDataElement *,char const *)" (?ReadDeviceSetConfigurationFromFile@PlusXmlUtils@@SA?AW4PlusStatus@@PEAVvtkXMLDataElement@@PEBD@Z)
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?SetDeviceSetConfigurationFileName@vtkPlusConfig@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (public: void __cdecl vtkPlusConfig::SetDeviceSetConfigurationFileName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported in function "class vtkSmartPointer<class vtkPlusOpenIGTLinkServer> __cdecl StartServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?StartServer@@YA?AV?$vtkSmartPointer@VvtkPlusOpenIGTLinkServer@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?GetDeviceSetConfigurationDirectory@vtkPlusConfig@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ (public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl vtkPlusConfig::GetDeviceSetConfigurationDirectory(void)) imported in function "public: static enum PlusStatus __cdecl PlusXmlUtils::ReadDeviceSetConfigurationFromFile(class vtkXMLDataElement *,char const *)" (?ReadDeviceSetConfigurationFromFile@PlusXmlUtils@@SA?AW4PlusStatus@@PEAVvtkXMLDataElement@@PEBD@Z)
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?SetDeviceSetConfigurationData@vtkPlusConfig@@QEAAXPEAVvtkXMLDataElement@@@Z (public: void __cdecl vtkPlusConfig::SetDeviceSetConfigurationData(class vtkXMLDataElement *)) imported in function "class vtkSmartPointer<class vtkPlusOpenIGTLinkServer> __cdecl StartServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?StartServer@@YA?AV?$vtkSmartPointer@VvtkPlusOpenIGTLinkServer@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
2>vtkPlusServerTest.obj : warning LNK4217: locally defined symbol ?New@vtkPlusTransformRepository@@SAPEAV1@XZ (public: static class vtkPlusTransformRepository * __cdecl vtkPlusTransformRepository::New(void)) imported in function "class vtkSmartPointer<class vtkPlusOpenIGTLinkServer> __cdecl StartServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?StartServer@@YA?AV?$vtkSmartPointer@VvtkPlusOpenIGTLinkServer@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
2>vtkPlusServerTest.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl PlusTransformName::PlusTransformName(class PlusTransformName const &)" (__imp_??0PlusTransformName@@QEAA@AEBV0@@Z) referenced in function "enum PlusStatus __cdecl ConnectClients(int,class std::vector<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource>,class std::allocator<class vtkSmartPointer<class vtkPlusOpenIGTLinkVideoSource> > > &,int,class vtkSmartPointer<class vtkXMLDataElement>)" (?ConnectClients@@YA?AW4PlusStatus@@HAEAV?$vector@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@V?$allocator@V?$vtkSmartPointer@VvtkPlusOpenIGTLinkVideoSource@@@@@std@@@std@@HV?$vtkSmartPointer@VvtkXMLDataElement@@@@@Z)
2>C:\_\PL17\bin\Release\vtkPlusServerTest.exe : fatal error LNK1120: 1 unresolved externals
2>Done building project "vtkPlusServerTest.vcxproj" -- FAILED.
10>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
10>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 1 failed, 70 up-to-date, 7 skipped ==========

```

**Comment by dzenanz** [comment] 2017-11-13 19:38
My local install is fully updated. Maybe that is the difference?

```
Microsoft Visual Studio Community 2017
Version 15.4.3
```

**Comment by lassoan** [comment] 2017-11-13 20:30
To confirm that you the problem and solution, could you please add these lines

    #include "PlusConfigure.h"
    #define PlusLib_STATIC

to the very beginning  of each cxx file that gives you the warning?

**Comment by dzenanz** [comment] 2017-11-13 20:46
The order of includes was wrong in the offending files. `PlusConfigure.h` was not the first Plus include. See the referencing pull requests.

**Comment by lassoan** [comment] 2017-11-13 21:23
Thank you, I've merged the two pull requests.
Can we close this issue?

**Closed** 2017-11-13 21:23 UTC
