### ISSUE TITLE
Need help with Plus config file for ascension 3D tracker

### ISSUE THREAD

**Issue by alankdkd** [PlusToolkit/PlusLib#277] opened 2017-11-22 19:54 UTC
Hi there.  I'm trying to configure a stylus from an ascension 3D tracker without success.  I'd like to display its position in real time over a CAT-scan image.  I suspect the `<PlusOpenIGTLinkServer>` element in my config file is incorrect.  Can someone look at the XML and tell me what I'm doing wrong?  Thanks!  Alan

PlusDeviceSet_Server_Ascension3DG.xml (modified):

```
<PlusConfiguration version="2.3">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: Ascension 3DG tracker"
      Description="Broadcasting tool tracking data through OpenIGTLink
Ascension3DG sensors should be plugged in to the Ascension3DG DriveBay mounted on Ultrasonix US in the following order from to leftmost slot (Transducer 1) to the right: 1  Reference, 2 Stylus." 
    />
    <Device
      Id="TrackerDevice" 
      Type="Ascension3DG" 
      FilterAcWideNotch="1"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        <!-- <DataSource Type="Tool" Id="Probe" PortName="0"  />  -->
        <DataSource Type="Tool" Id="Reference" PortName="0"  />
        <DataSource Type="Tool" Id="Stylus" PortName="1"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
     <!--     <DataSource Id="Probe"/>  -->
          <DataSource Id="Reference"/>
          <DataSource Id="Stylus"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualDiscCapture"
      BaseFilename="RecordingTest.mha"
      EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device>
  </DataCollection>

  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="6000" 
    OutputChannelId="TrackerStream" > 
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="IMAGE" />
      	<Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames> 
        <!--  <Transform Name="ProbeToTracker" />  -->
        <Transform Name="ReferenceToTracker" />
        <!--  <Transform Name="StylusToTracker" />  -->
        <Transform Name="StylusTipToReference" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>
<PlusConfiguration version="2.3">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: Ascension 3DG tracker"
      Description="Broadcasting tool tracking data through OpenIGTLink
Ascension3DG sensors should be plugged in to the Ascension3DG DriveBay mounted on Ultrasonix US in the following order from to leftmost slot (Transducer 1) to the right: 1  Reference, 2 Stylus." 
    />
    <Device
      Id="TrackerDevice" 
      Type="Ascension3DG" 
      FilterAcWideNotch="1"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        <!-- <DataSource Type="Tool" Id="Probe" PortName="0"  />  -->
        <DataSource Type="Tool" Id="Reference" PortName="0"  />
        <DataSource Type="Tool" Id="Stylus" PortName="1"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
     <!--     <DataSource Id="Probe"/>  -->
          <DataSource Id="Reference"/>
          <DataSource Id="Stylus"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualDiscCapture"
      BaseFilename="RecordingTest.mha"
      EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device>
  </DataCollection>

  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="6000" 
    OutputChannelId="TrackerStream" > 
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="IMAGE" />
      	<Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames> 
        <!--  <Transform Name="ProbeToTracker" />  -->
        <Transform Name="ReferenceToTracker" />
        <!--  <Transform Name="StylusToTracker" />  -->
        <Transform Name="StylusTipToReference" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>
```

**Comment by alankdkd** [comment] 2017-11-22 19:55
The XML didn't come through (I tried bolding it).  Here it is:

<PlusConfiguration version="2.3">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: Ascension 3DG tracker"
      Description="Broadcasting tool tracking data through OpenIGTLink
Ascension3DG sensors should be plugged in to the Ascension3DG DriveBay mounted on Ultrasonix US in the following order from to leftmost slot (Transducer 1) to the right: 1  Reference, 2 Stylus." 
    />
    <Device
      Id="TrackerDevice" 
      Type="Ascension3DG" 
      FilterAcWideNotch="1"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        
        <DataSource Type="Tool" Id="Reference" PortName="0"  />
        <DataSource Type="Tool" Id="Stylus" PortName="1"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
     
          <DataSource Id="Reference"/>
          <DataSource Id="Stylus"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualDiscCapture"
      BaseFilename="RecordingTest.mha"
      EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device>
  </DataCollection>

  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="6000" 
    OutputChannelId="TrackerStream" > 
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="IMAGE" />
      	<Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames> 
        
        <Transform Name="ReferenceToTracker" />
        
        <Transform Name="StylusTipToReference" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>

**Comment by lassoan** [comment] 2017-11-22 19:56
You need to use the "Insert code" format style to display XML string as verbatim text.

**Comment by alankdkd** [comment] 2017-11-22 19:59
Thanks lassoan!

**Comment by lassoan** [comment] 2017-11-22 20:00
The problem is that you try to send StylusTipToReference transform without specifying StylusTipToStylus.

Probably the simplest is to send StylusToReference, compute StylusTipToStylus in Slicer using pivot calibration, and add this computed StylusTipToStylus transform to the config file (either manually copying the values or using PlusRemote module in Slicer).

There are many tutorials about pivot calibration on SlicerIGT website: http://www.slicerigt.org/wp/user-tutorial/

**Comment by alankdkd** [comment] 2017-11-22 20:02
Thanks again lassoan! I'll look at it.

**Comment by alankdkd** [comment] 2017-11-27 21:37
Hi Andras,

I've been trying to follow the tutorials (U-02, U-04, U-09, and U-11), but there are often directions that don't match the version of 3dSlicer I'm using (4.8).

For example, I'm trying the Pivot Calibration tutorial (https://onedrive.live.com/view.aspx?resid=7230D4DEC6058018!3128&ithint=file%2cpptx&app=PowerPoint&authkey=!AMy-wgNHStEKsPU), and in Slide 9 (Load data example), it says "Load SlicerIGT-Data/Skull_StylusCalibration.mrb", but there's no data set like that in the Data Store.

I inserted a StylusTipToStylus transform.  Then to create a needle model, it says "In Data module Drag-and-drop needle model on StylusTipToStylus".  There's no clue how to do this.  I can find nothing in the Data module that even mentions a needle.  Nothing under Models either.

Can you help me display a stylus on my image? 

Thanks!
Alan

**Comment by alankdkd** [comment] 2017-11-28 17:10
Hi Andras, never mind - I found the Extension Manager and was able to install Slicer/IGT.  It was very easy, but it took me a couple of hours to find it.  Maybe adding a note to tutorial U-11 on HOW to add a needle would save time for other readers.

Now on Slide 6, it says "Make sure the Sequences toolbar is visible".  But under View | Toolbars, there is no Sequence Browser.  Oh well, I'll find it.  Eventually...

**Comment by Sunderlandkyl** [comment] 2017-11-28 17:16
Have you installed the sequences extension?
You should be able to find it by searching in the extension manager.

**Comment by alankdkd** [comment] 2017-11-28 19:53
Found Sequence Browser, and continued with tutorial U-11.  When I got to Pivot Calibration, the result was: "Pivot calibration failed: Not enough input transforms are available".

I was starting with a preexisting CAT scan model.  The hierarchy under Data | Transform hierarchy is unclear, and I probably have it set up wrong.  Under Scene is: Default Scene Camera, 1: Unnamed Series (my CAT scan), StylusToReference, StylusTipToStylus (indented), NeedleModel (indented).  At the bottom is Output Geometry.

It looks like the transform hierarchy is wrong.  I'll see if I can find some documentation on it.

**Comment by alankdkd** [comment] 2017-11-28 19:54
Sunderlandkyl: Yes, I found it.  Thanks.

**Comment by lassoan** [comment] 2017-11-28 21:24
@ungi Could you please update the tutorials based on the feedback above?

**Comment by alankdkd** [comment] 2017-11-28 22:17
OK, I was able to connect the tracker/stylus to Slicer/Plus.  The port numbers didn't match, which took a while to figure out; Plus uses port 6000, and Slicer defaulted to 18944.  (Maybe add a tutorial tip to watch for this in OpenIGTLinkIF.)

The transforms ReferenceToTracker, StylusToReference, and StylusTipToStylus are working, but I can't make the needle in the scene track stylus movements yet.

**Comment by alankdkd** [comment] 2017-11-28 22:34
I have a question about the position/orientation sensor on the stylus:  The diagram in tutorial U11, Slide 3 shows the "position marker" (sensor) to be co-linear with the stylus.

We're using a custom-designed stylus and a surgical drill that has the sensor attached to the side of the tool, i.e. it's offset from the tool axis by about a centimeter.  Will this still be accurate with the pivot-calibration algorithm?

**Comment by lassoan** [comment] 2017-11-29 02:40
Pivot calibration can take care of aligning the axis as well (spin calibration step).

**Comment by ungi** [comment] 2017-11-29 03:41
I will update the tutorials hopefully by the end of the year. Until then, I recommend the U-37 tutorial, which includes pivot calibration, and it was done with Slicer 4.8.

**Comment by alankdkd** [comment] 2017-11-29 15:19
Thanks ungi!

**Comment by alankdkd** [comment] 2017-11-29 16:47
Some inaccuracies in Tutorial U04, Coordinate Transforms:

1. Slide 6, Step 2: Should be "Create new Linear Transform as..."
2. Slide 7, Step 2: There is no Create model button; should be "Create coordinate system".
3. Slide 7:  Add pressing Create cube; it's assumed on Slide 8.

**Comment by adamrankin** [comment] 2017-12-13 20:25
@ungi Would you have time to make these corrections? (disregard if already completed).

If so, could we close this issue?

**Closed** 2017-12-16 13:51 UTC
