### ISSUE TITLE
Enabling VP9 causes build issues

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#421] opened 2018-10-01 13:32 UTC
```text
17>------ Build started: Project: vtkTransformRepositoryTest, Configuration: Debug x64 ------
18>------ Build started: Project: AccurateTimerTest, Configuration: Debug x64 ------
19>------ Build started: Project: BrainLabTrackerSim, Configuration: Debug x64 ------
20>------ Build started: Project: CompareVolumes, Configuration: Debug x64 ------
21>------ Build started: Project: EditSequenceFile, Configuration: Debug x64 ------
22>------ Build started: Project: PlusCommonTest, Configuration: Debug x64 ------
23>------ Build started: Project: PlusMathTest, Configuration: Debug x64 ------
24>------ Build started: Project: vtkPlusLoggerTest, Configuration: Debug x64 ------
6>  vtkPlusHaptics.vcxproj -> C:\Dev\PlusGit\bin64wp\lib\Debug\vtkPlusHaptics.lib
14>  vtkPlusRendering.vcxproj -> C:\Dev\PlusGit\bin64wp\lib\Debug\vtkPlusRendering.lib
25>------ Build started: Project: vtkPlusCalibration, Configuration: Debug x64 ------
26>------ Build started: Project: ModelRenderer, Configuration: Debug x64 ------
13>  vtkPlusImageProcessing.vcxproj -> C:\Dev\PlusGit\bin64wp\lib\Debug\vtkPlusImageProcessing.lib
16>  vtkPlusVolumeReconstruction.vcxproj -> C:\Dev\PlusGit\bin64wp\lib\Debug\vtkPlusVolumeReconstruction.lib
27>------ Build started: Project: vtkPlusUsSimulator, Configuration: Debug x64 ------
28>------ Build started: Project: ExtractScanLines, Configuration: Debug x64 ------
29>------ Build started: Project: DrawScanLines, Configuration: Debug x64 ------
30>------ Build started: Project: EnhanceUsTrpSequence, Configuration: Debug x64 ------
31>------ Build started: Project: CreateSliceModels, Configuration: Debug x64 ------
15>  vtkPlusOpenIGTLink.vcxproj -> C:\Dev\PlusGit\bin64wp\lib\Debug\vtkPlusOpenIGTLink.lib
17>LINK : fatal error LNK1104: cannot open file 'webm.lib'
32>------ Build started: Project: DrawClipRegion, Configuration: Debug x64 ------
33>------ Build started: Project: RfProcessor, Configuration: Debug x64 ------
24>LINK : fatal error LNK1104: cannot open file 'webm.lib'
19>LINK : fatal error LNK1104: cannot open file 'webm.lib'
34>------ Build started: Project: ScanConvert, Configuration: Debug x64 ------
22>LINK : fatal error LNK1104: cannot open file 'webm.lib'
35>------ Build started: Project: VolumeReconstructor, Configuration: Debug x64 ------
23>LINK : fatal error LNK1104: cannot open file 'webm.lib'
27>  vtkPlusUsSimulator.vcxproj -> C:\Dev\PlusGit\bin64wp\lib\Debug\vtkPlusUsSimulator.lib
21>LINK : fatal error LNK1104: cannot open file 'webm.lib'
18>LINK : fatal error LNK1104: cannot open file 'webm.lib'
28>LINK : fatal error LNK1104: cannot open file 'webm.lib'
26>LINK : fatal error LNK1104: cannot open file 'webm.lib'
34>LINK : fatal error LNK1104: cannot open file 'webm.lib'
33>LINK : fatal error LNK1104: cannot open file 'webm.lib'
36>------ Build started: Project: vtkPlusDataCollection, Configuration: Debug x64 ------
20>LINK : fatal error LNK1104: cannot open file 'webm.lib'
37>------ Build started: Project: vtkPlusUsSimulatorTest, Configuration: Debug x64 ------
25>  vtkPlusCalibration.vcxproj -> C:\Dev\PlusGit\bin64wp\lib\Debug\vtkPlusCalibration.lib
38>------ Build started: Project: vtkLineSegmentationAlgoTest, Configuration: Debug x64 ------
29>LINK : fatal error LNK1104: cannot open file 'webm.lib'
35>LINK : fatal error LNK1104: cannot open file 'webm.lib'
32>LINK : fatal error LNK1104: cannot open file 'webm.lib'
30>LINK : fatal error LNK1104: cannot open file 'webm.lib'
37>LINK : fatal error LNK1104: cannot open file 'webm.lib'
31>LINK : fatal error LNK1104: cannot open file 'webm.lib'
38>LINK : fatal error LNK1104: cannot open file 'webm.lib'
36>  vtkPlusWinProbeVideoSource.cxx
```

**Comment by dzenanz** [comment] 2018-10-01 15:18
I tried disabling VP9. After removing PlusLib-bin and building again, now I am running into this:
`C:\Dev\PlusGit\bin64wp\PlusLib\src\PlusCommon\IO\vtkPlusMkvSequenceIO.cxx(15): fatal error C1083: Cannot open include file: 'igtlCodecCommonClasses.h': No such file or directory [C:\Dev\PlusGit\bin64wp\PlusLib-bin\src\PlusCommon\vtkPlusCommon.vcxproj]`
I will try a clean build.

**Comment by dzenanz** [comment] 2018-10-01 18:53
This does not happen in a completely clean build and with the problematic options turned off.

**Comment by Sunderlandkyl** [comment] 2018-10-01 18:57
Which options did you enable to cause the issue?

**Comment by dzenanz** [comment] 2018-10-01 19:13
PLUS_ENABLE_VIDEOSTREAMING and PLUS_USE_VTKVIDEOIO_MKV. The other options were my usual options which work. I remember seeing and enabling VP9 option in my first attempt, but I don't see it now.

**Comment by Sunderlandkyl** [comment] 2018-10-01 19:41
Great, I'll make a test build with those options enabled.
I think that the PLUS_USE_VP9 appears if PLUS_ENABLE_VIDEOSTREAMING is enabled.

For now, most of the compressed video features are unstable and subject to change as I implement the shared functionality for compressed video IO between Plus and Slicer.

**Comment by Sunderlandkyl** [comment] 2018-10-11 20:16
Sorry for not getting around to this quickly. I wasn't able to reproduce it initially, but it seems to only be a problem for static builds.

I'll see what I can do.

**Comment by dzenanz** [comment] 2018-10-11 20:35
I tried to enable that out of curiosity, not because I needed it 😄

**Comment by adamrankin** [comment] 2018-11-15 00:41
The issue comes from PLUS_USE_VTKVIDEOIO_MKV I think. For some reason it is passing webm as a dependency, when it shouldn't. Digging further.

**Comment by adamrankin** [comment] 2018-11-15 00:48
I can confirm that manually removing 
`;\$<LINK_ONLY:webm>`
from IGSIOTargets.cmake removes the phantom webm.lib from the links.

However, the build still fails with a large number of missing external symbols.

**Comment by lassoan** [comment] 2021-02-07 16:03
Is this still an issue?

**Comment by lassoan** [comment] 2021-06-02 18:41
Nobody complained about this since 2018, closing it.

**Closed by lassoan** 2021-06-02 18:41 UTC
Labels: Static, bug
