### ISSUE TITLE
Add request model by name command

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#165] opened 2017-09-21 18:32 UTC
(No description)

Migrated from https://app.assembla.com/spaces/plus/tickets/1138/details

**Comment by Sunderlandkyl** [comment] 2017-09-21 18:32
2017-01-10 13:50
Adam Rankin
test #1138 Adding handling of GET_POLYDATA message
Committed to: plus
In plus:5015

2017-07-16 10:03
Adam Rankin
re #1138 converting from GET_POLYDATA v2 style query to Plus style command query

Branch: master
Commit: plus:054fe2148d

2017-07-16 10:05
Adam Rankin
re #1213 adding first pass implementation of RTSP video device

currently crashes when trying to write frame to buffer (deep in vtkImageData deepcopy) so more investigation needed

temporary change to include new volume query method

re #1138 converting from GET_POLYDATA v2 style query to Plus style command query

Branch: master
Commit: plus:56dd24bcca

2017-08-10 19:42
Adam Rankin
re #1138 improving Plus command response to also properly populate metadata fields relating to command responses

fixing minor bugs in command response values being hardcoded

renaming vtkPlusCommandCommandResponse to vtkPlusCommandRTSCommandResponse for clarity about classes intended purpose (send RTS_COMMAND back to client)

Branch: plusserver_command_metadata
Commit: plus:240d8d7a91

2017-08-29 12:14
Adam Rankin
re #1138 improving Plus command response to also properly populate metadata fields relating to command responses (#70)

fixing minor bugs in command response values being hardcoded

renaming vtkPlusCommandCommandResponse to vtkPlusCommandRTSCommandResponse for clarity about classes intended purpose (send RTS_COMMAND back to client)

Branch: master
Commit: plus:f0c906415a

**Comment by lassoan** [comment] 2017-09-29 14:46
@adamrankin It seems that we'll be ready for a new stable version within a week (depending on what we decide to include from OptiTrack developments). Do you think you can close this issue by then or can this be postponed to be fixed after the stable release?

**Comment by adamrankin** [comment] 2017-09-29 14:48
Yes, in fact this is a duplicate of GetPolydata issue.

**Closed by adamrankin** 2017-09-29 14:48 UTC
Labels: PlusLib-PlusServer
