### ISSUE TITLE
hot to use the calibration config file in PLUS 

### ISSUE THREAD

**Issue by salimohamadi** [PlusToolkit/PlusLib#379] opened 2018-07-11 10:29 UTC
Hi,
I have done the calibration steps in fcal and a .xml file has been generated including a lot of information. I would like to know if all the information should be copied in the config file?
if not which parts should be copied?
unfortunately, it could not be attached, so I will copy it here

Thanks
Samaneh Alimohamadi

```
<PlusConfiguration version="2.5" PlusRevision="Plus-2.6.0.d3024ea5 - Win32">
  <DataCollection StartupDelaySec="1">
    <DeviceSet Name="fCal: Telemed (L12 probe) + NDI Aurora Tracker (Probe, Reference, Stylus) - fCal phantom 2.1 " Description="Telemed and NDI Aurora Tracker Both Data Acquisition" />
    <Device
      Id="TrackerDevice"
      Type="AuroraTracker"
      SerialPort="1"
      ToolReferenceFrame="Tracker"
      BaudRate="0"
      MeasurementVolumeNumber="0"
      LocalTimeOffsetSec="0.0190003">
      <DataSources>
        <DataSource Type="Tool" Id="Stylus" PortName="0" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02100000
            </NdiIdentity>
            <PartNumber>
              610065   T6E0-S00198
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A198400
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02100000
            </NdiIdentity>
            <PartNumber>
              610065   T6E0-S00198
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A198400
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02100000
            </NdiIdentity>
            <PartNumber>
              610065   T6E0-S00198
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A198400
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02100000
            </NdiIdentity>
            <PartNumber>
              610065   T6E0-S00198
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A198400
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02100000
            </NdiIdentity>
            <PartNumber>
              610065   T6E0-S00198
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A198400
            </SerialNumber>
          </CustomProperties>
        </DataSource>
        <DataSource Type="Tool" Id="Reference" PortName="1" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
        </DataSource>
        <DataSource Type="Tool" Id="Probe" PortName="2" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
        </DataSource>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
          <DataSource Id="Stylus" />
          <DataSource Id="Reference" />
          <DataSource Id="Probe" />
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="VideoDevice"
      Type="TelemedVideo"
      DepthMm="-1"
      FrequencyMhz="-1"
      DynRangeDb="-1"
      GainPercent="-1"
      PowerPercent="-1">
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="MF" BufferSize="150" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device Id="TrackedVideoDevice" Type="VirtualMixer">
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream" />
      </OutputChannels>
    </Device>
  </DataCollection>
  <CoordinateDefinitions>
    <Transform From="Image" To="Probe"
      Matrix="
        0.045822	0.0139972	-0.0910916	-18.6939
        -0.0951283	-0.00178489	-0.044953	18.0128
        -0.00836478	0.0976929	0.01223	39.4495
        0	0	0	1"
       Error="1.31009" Date="071118_140800" />
    <Transform From="Image" To="TransducerOriginPixel"
      Matrix="
        1	0	0	-410
        0	1	0	5
        0	0	1	0
        0	0	0	1"
       Date="2011.12.06 17:57:00" />
    <Transform From="Phantom" To="Reference"
      Matrix="
        0.86722	-0.497686	0.015436	-89.1862
        0.497797	0.865878	-0.049534	-57.2198
        0.0112867	0.0506409	0.998653	-38.0795
        0	0	0	1"
       Error="0.820381" Date="071118_134455" />
    <Transform From="StylusTip" To="Stylus"
      Matrix="
        0.986123	0	-0.166018	-0.150332
        -0.0245496	-0.989006	-0.145821	-0.132043
        -0.164193	0.147873	-0.975282	-0.883131
        0	0	0	1"
       Error="0.0995752" Date="061718_165544" />
    <Transform From="TransducerOriginPixel" To="TransducerOrigin"
      Matrix="
        0.10592	0	0	0
        0	0.0987066	0	0
        0	0	0.102313	0
        0	0	0	1"
       Date="071118_140800" />
  </CoordinateDefinitions>
  <Rendering WorldCoordinateFrame="Reference" DisplayedImageOrientation="MFA">
    <DisplayableObject Type="Model" ObjectCoordinateFrame="TransducerOrigin" Id="ProbeModel" File="Probe_L12.stl"
      ModelToObjectTransform="
        -1	0	0	29.7
        0	-1	0	1.5
        0	0	1	-14
        0	0	0	1" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="Reference" Id="Volume" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="StylusTip" Id="StylusModel" File="Stylus_Example.stl" />
    <DisplayableObject
      Id="PhantomModel"
      Type="Model"
      ObjectCoordinateFrame="Phantom"
      Opacity="0.6"
      File="fCal_2.1.stl"
      ModelToObjectTransform="
        1	0	0	0
        0	1	0	0
        0	0	1	0
        0	0	0	1" />
    <DisplayableObject Type="Image" ObjectCoordinateFrame="Image" Id="LiveImage" />
  </Rendering>
  <Segmentation
    ApproximateSpacingMmPerPixel="0.0911669"
    MorphologicalOpeningCircleRadiusMm="0.21"
    MorphologicalOpeningBarSizeMm="1.01"
    ClipRectangleOrigin="29 29"
    ClipRectangleSize="424 424"
    MaxLinePairDistanceErrorPercent="10"
    AngleToleranceDegrees="10"
    MaxAngleDifferenceDegrees="10"
    MinThetaDegrees="-70"
    MaxThetaDegrees="70"
    MaxLineShiftMm="10"
    ThresholdImagePercent="5.1"
    CollinearPointsMaxDistanceFromLineMm="0.6"
    UseOriginalImageIntensityForDotIntensityScore="0" />
  <PhantomDefinition>
    <Description Name="fCAL" Type="Multi-N" Version="2.1" WiringVersion="2.5" Institution="Queen&apos;s University PerkLab" />
    <Geometry>
      <Pattern Type="NWire">
        <Wire Name="7:G1_g1" EndPointFront="30.0 0.0 0.0" EndPointBack="30.0 0.0 40.0" />
        <Wire Name="8:L1_h1" EndPointFront="55.0 0.0 0.0" EndPointBack="35.0 0.0 40.0" />
        <Wire Name="9:M1_m1" EndPointFront="60.0 0.0 0.0" EndPointBack="60.0 0.0 40.0" />
      </Pattern>
      <Pattern Type="NWire">
        <Wire Name="4:G3_g3" EndPointFront="30.0 10.0 0.0" EndPointBack="30.0 10.0 40.0" />
        <Wire Name="5:H3_l3" EndPointFront="35.0 10.0 0.0" EndPointBack="55.0 10.0 40.0" />
        <Wire Name="6:M3_m3" EndPointFront="60.0 10.0 0.0" EndPointBack="60.0 10.0 40.0" />
      </Pattern>
      <Pattern Type="NWire">
        <Wire Name="1:H5_h5" EndPointFront="35.0 20.0 0.0" EndPointBack="35.0 20.0 40.0" />
        <Wire Name="2:L5_i5" EndPointFront="55.0 20.0 0.0" EndPointBack="40.0 20.0 40.0" />
        <Wire Name="3:M5_m5" EndPointFront="60.0 20.0 0.0" EndPointBack="60.0 20.0 40.0" />
      </Pattern>
      <Landmarks>
        <Landmark Name="#1" Position="-32.53 -5.25 45.0" />
        <Landmark Name="#2" Position="-32.53 -5.25  5.0" />
        <Landmark Name="#3" Position="-32.53 19.75 -5.0" />
        <Landmark Name="#4" Position="-32.53 19.75 45.0" />
        <Landmark Name="#5" Position="105.47 -5.25 -5.0" />
        <Landmark Name="#6" Position="105.47 -5.25 45.0" />
        <Landmark Name="#7" Position="105.47 14.75 -5.0" />
        <Landmark Name="#8" Position="105.47 19.75 45.0" />
        <Landmark Name="#9" Position=" -3.53 -9.25 45.0" />
        <Landmark Name="#10" Position=" 41.47 -9.25 45.0" />
        <Landmark Name="#11" Position=" 86.47 -9.25 45.0" />
        <Landmark Name="#12" Position=" 96.47 -9.25 30.0" />
        <Landmark Name="#13" Position=" 86.47 -9.25 -5.0" />
        <Landmark Name="#14" Position=" 21.47 -9.25 -5.0" />
        <Landmark Name="#15" Position=" -3.53 -9.25 -5.0" />
        <Landmark Name="#16" Position="-13.53 -9.25 10.0" />
      </Landmarks>
    </Geometry>
  </PhantomDefinition>
  <VolumeReconstruction
    OutputSpacing="0.5 0.5 0.5"
    ClipRectangleOrigin="0 0"
    ClipRectangleSize="820 616"
    Interpolation="LINEAR"
    Optimization="FULL"
    CompoundingMode="MEAN"
    FillHoles="OFF" />
  <fCal
    PhantomModelId="PhantomModel"
    ReconstructedVolumeId="Volume"
    TransducerModelId="ProbeModel"
    StylusModelId="StylusModel"
    ImageDisplayableObjectId="LiveImage"
    NumberOfCalibrationImagesToAcquire="200"
    NumberOfValidationImagesToAcquire="100"
    NumberOfStylusCalibrationPointsToAcquire="200"
    RecordingIntervalMs="100"
    MaxTimeSpentWithProcessingMs="70"
    ImageCoordinateFrame="Image"
    ProbeCoordinateFrame="Probe"
    ReferenceCoordinateFrame="Reference"
    TransducerOriginCoordinateFrame="TransducerOrigin"
    TransducerOriginPixelCoordinateFrame="TransducerOriginPixel"
    TemporalCalibrationDurationSec="10"
    FixedChannelId="VideoStream"
    FixedSourceId="Video"
    MovingChannelId="TrackerStream"
    MovingSourceId="ProbeToTracker"
    DefaultSelectedChannelId="TrackedVideoStream"
    FreeHandStartupDelaySec="5" />
  <vtkPlusPivotCalibrationAlgo ObjectMarkerCoordinateFrame="Stylus" ReferenceCoordinateFrame="Reference" ObjectPivotPointCoordinateFrame="StylusTip" />
  <vtkPlusPhantomLandmarkRegistrationAlgo PhantomCoordinateFrame="Phantom" ReferenceCoordinateFrame="Reference" StylusTipCoordinateFrame="StylusTip" DetectionTimeSec="1.0" StylusTipMaximumDisplacementThresholdMm="1.8" />
  <vtkPlusProbeCalibrationAlgo ImageCoordinateFrame="Image" ProbeCoordinateFrame="Probe" PhantomCoordinateFrame="Phantom" ReferenceCoordinateFrame="Reference" />
</PlusConfiguration>

```

**Comment by lassoan** [comment] 2018-07-11 13:51
CustomProperties elements are for information only. All other elements may be used for certain operations. If you only need the probe's spatial calibration matrix then don't copy anything else than the `<Transform From="Image" To="Probe" ...>` element

**Comment by Sunderlandkyl** [comment] 2018-07-11 14:08
Duplicate of #380

**Closed** 2018-11-12 22:04 UTC
Labels: question
