### ISSUE TITLE
Cannot connect to NDI Polaris Vega with Plus Server Launcher

### ISSUE THREAD

**Issue by AndreDorigan** [PlusToolkit/PlusLib#519] opened 2019-03-28 10:43 UTC
Hello,

I haven't managed to connect to the NDI Polaris Vega using the Plus Server Launcher. I always get the message "Connection failed!", although the device is plugged in and working fine with the NDI software.

In the config file I have replaced the tool with the one I am using and have saved the .rom file in the correct folder, but this did not seem to solve the problem. I have attached the log and config files, if that helps.

<img width="1144" alt="config1" src="https://user-images.githubusercontent.com/20545651/55159516-7d74e080-5161-11e9-8fe6-56c7a862c111.png">

<img width="1140" alt="config2" src="https://user-images.githubusercontent.com/20545651/55159517-7d74e080-5161-11e9-93c8-4cb1fd66ecee.png">

[100617_094842_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3017990/100617_094842_PlusLog.txt)

Thank you in advance!

**Comment by AndreDorigan** [comment] 2019-03-28 10:48
[100617_094842_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3017525/100617_094842_PlusLog.txt)

**Comment by adamrankin** [comment] 2019-03-28 14:33
Hi, would you mind trying with one of the ROM files distributed with plus?
The main error is that it was unable to send the ROM file to the tracker.

Even if you don't have the hardware, the tracker can start tracking with
any ROM file.

**Comment by AndreDorigan** [comment] 2019-03-28 14:38
Hi, I did that and still have the same error
[032819_153639_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3018467/032819_153639_PlusLog.txt)

**Comment by adamrankin** [comment] 2019-03-28 14:55
You got a different error this time.

`Couldn't find srom file
C:/Users/MITI-Student/PlusApp-2.6.0.20190221-Win64/config/NdiToolDefinitions/8700399.rom`

If you're using a gui you can click the red circle to see the log and
identify the error. Could you try resolving the error and see if it works?

**Comment by AndreDorigan** [comment] 2019-03-28 15:00
By clicking on it I can see that every time I try to connect to the Polaris Vega, I get the following messages:

|INFO|1233.175000| Server process started successfully| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(213)

|ERROR|1234.602000| Server process error: Crashed| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(444)

|ERROR|1234.603000| Server stopped unexpectedly. Return code: -1073741819| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(457)

|INFO|1234.604000| Disconnect request successful| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(307)

**Comment by adamrankin** [comment] 2019-03-28 15:05
Hmm, something is funny here.

Basic questions:
How is the vega connected, usb or ethernet?

Is the Track software also running? Is it connected to tracker when you try
to start plus server?

Does Track successfully connect and load your ROM file?

**Comment by AndreDorigan** [comment] 2019-03-28 15:12
The Vega is connected with an ethernet cable going into an ethernet-USB adapter.

I have already tried to solve it by resetting and unplugging everything. I have tried with both XML scripts: the one for the Polaris, which came with the download, and for the Polaris Vega, which was used as an example on the website.

When I use the NDI software, it tracks any of the tools perfectly. I have tried connecting the Vega with the Plus Server Launcher with the NDI software both on and off.

**Comment by adamrankin** [comment] 2019-03-28 20:30
When connecting using the Track software, do you see a serial port number
in the title bar?

Can you post your config file?

**Comment by AndreDorigan** [comment] 2019-03-29 08:09
All I managed to find was the remote IP port number (you can see it in the "connections" file). Thanks for the help so far!

[PlusDeviceSet_Server_NDIPolaris.txt](https://github.com/PlusToolkit/PlusLib/files/3021634/PlusDeviceSet_Server_NDIPolaris.txt)

[System configuration.txt](https://github.com/PlusToolkit/PlusLib/files/3021635/System.configuration.txt)

[Connections.txt](https://github.com/PlusToolkit/PlusLib/files/3021636/Connections.txt)

**Comment by adamrankin** [comment] 2019-03-29 13:16
Ok, I think you need to connect via ethernet? Can you try with the example Vega configuration file and replace the IP and port with the ones from Connections.txt?

**Comment by AndreDorigan** [comment] 2019-03-29 13:44
I have tried connecting via ethernet, but it doesn't work (even with the NDI tracking software). 

I updated the IP and port according to the current settings from the NDI tracking software and attempted to connect it using the following config files, but it still won't work. Is it possible to know if there might beanything missing from the installation?

[PlusDeviceSet_Server_NDIPolaris.txt](https://github.com/PlusToolkit/PlusLib/files/3022886/PlusDeviceSet_Server_NDIPolaris.txt)

[PlusDeviceSet_Server_NDIPolarisVega.txt](https://github.com/PlusToolkit/PlusLib/files/3022887/PlusDeviceSet_Server_NDIPolarisVega.txt)

**Comment by AndreDorigan** [comment] 2019-04-03 07:20
Or is there any other way to get access to the data transmitted by the Polaris Vega directly on Matlab?

**Comment by adamrankin** [comment] 2019-04-03 14:40
I will try and set ours up today and confirm I can still connect.

**Comment by adamrankin** [comment] 2019-04-03 15:03
I am able to connect and stream transforms from our Vega using the latest. We are using a POE-injector and an ethernet connection, and my config file is as follows

```xml
...
  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet
      Name="PlusServer: NDI Vega tracker with passive markers"
      Description="Broadcasting tool tracking data through OpenIGTLink
For NDI Vega: Tool (8700339), Stylus (8700340), Reference (8700449)" />
    <Device
      Id="TrackerDevice"
      Type="NDITracker"
      NetworkHostname="P9-00312"
      NetworkPort="8765"
      ToolReferenceFrame="Reference" >
      <DataSources>
        <DataSource Type="Tool" Id="Stylus" RomFile="NdiToolDefinitions/8700248.rom"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
          <DataSource Id="Stylus"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
...
```

**Comment by adamrankin** [comment] 2019-04-03 15:04
P9-00312 is it's Bonjour name, perhaps you could try the same?

**Comment by AndreDorigan** [comment] 2019-04-03 15:22
Hi, I've tried it once again with your config file...
[config.txt](https://github.com/PlusToolkit/PlusLib/files/3039379/config.txt)

... and I am still getting "connection failed":
[040319_171041_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3039380/040319_171041_PlusLog.txt)

This is the way the device is set up to work with the NDI tracking software:
![file1](https://user-images.githubusercontent.com/20545651/55490940-e57d6800-5634-11e9-9345-04455bed2abf.jpeg)

And the adapter up close:
![file](https://user-images.githubusercontent.com/20545651/55490956-edd5a300-5634-11e9-8d0a-7b78e7072a70.jpeg)

**Comment by adamrankin** [comment] 2019-04-03 16:15
Remove the video device and mixer device, and update the plus server to use the tracker stream. Post the log after those changes

**Comment by AndreDorigan** [comment] 2019-04-04 11:46
So after removing the devices and attempting to launch the server with the Vega config file:

[text.txt](https://github.com/PlusToolkit/PlusLib/files/3043272/text.txt)

**Comment by adamrankin** [comment] 2019-04-04 13:49
Are you able to find the log file of the server, and not the plus server launcher?

**Comment by AndreDorigan** [comment] 2019-04-04 13:58
Where are those files saved? The only log files I could find are the ones saved in the "data" folder

**Comment by adamrankin** [comment] 2019-04-04 14:25
I believe it's in the <bin>\output directory, where <bin> depends on whether it was built, installed as user, or installed as admin

**Comment by AndreDorigan** [comment] 2019-04-04 15:11
I looked through all files and couldn't find any server log files. I couldn't find an "output" folder, and the only files in the PlusTools "bin" folder are .dll and .exe files

**Comment by adamrankin** [comment] 2019-04-05 15:21
Could you search for .txt files modified by date on your disk?

**Comment by AndreDorigan** [comment] 2019-04-08 09:41
I tried to set up the server using the PlusServer Launcher with and without the Polaris connected, these were the log files saved in the "bin/output/" folder:

Nothing plugged in:
[040819_102320_PlusLog (1 - no device connected).txt](https://github.com/PlusToolkit/PlusLib/files/3053681/040819_102320_PlusLog.1.-.no.device.connected.txt)

Polaris Vega plugged in:
[040819_112428_PlusLog (2 -- device connected).txt](https://github.com/PlusToolkit/PlusLib/files/3053682/040819_112428_PlusLog.2.--.device.connected.txt)

**Comment by adamrankin** [comment] 2019-04-08 14:27
Is there anything else plugged into the computer? I honestly can't figure out what's going on. You shouldn't even see the "Serial port write error" because it shouldn't be using the serial port...

**Comment by AndreDorigan** [comment] 2019-04-08 15:41
There are no other devices connected to the computer.

I reconnected the Vega now directly with ethernet and had to configure the network again, so now the ethernet connection is working fine with the NDI software. Still, this is the error I am getting while trying to launch the Plus Server this way:

[040819_173437_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3055128/040819_173437_PlusLog.txt)

**Comment by m-luo92** [comment] 2020-02-05 23:37
Is there any update on this issue? I am having the same problem as above.

**Comment by adamrankin** [comment] 2020-02-15 16:00
Can we organize a Skype session? Our Vega is working as expected.

**Comment by MaDiBmDaD** [comment] 2020-07-28 04:45
I am using VEGA- Ethernet and have the same problem in connection failed by Plus Server Launcher. Although Tool (8700339) are updated but also have change either Stylus (8700340) or Reference?

**Comment by xiangb2** [comment] 2021-01-28 18:13
I am using VEGA- Ethernet and have the same problem in connection failed by Plus Server Launcher. My computer is windows 10 x64.

**Comment by tggadda** [comment] 2021-01-29 00:24
I had the same problem above but determined it was caused by using the wrong NetworkHostname and NetworkPort. It looks like NetworkPort is probably always going to be 8765 (but you can check in NDI Configure) and I just used the Bonjour name from the top left corner of my NDI Tracker when it was connected to the system.

**Comment by adamrankin** [comment] 2021-01-29 01:39
Yes, using an IP has to be configured in the Configure NDI application. By default IP services are turned off (as you've discovered).

**Comment by arciasan** [comment] 2021-02-04 16:43
Hi,
How do you check the IP services? I am having the same problem, I can't connect to NDI Polaris Vega using the Plus Server Launcher. I am using the NetworkHostname and NetworkPort that I get from NDI software, however, I still have this error: 

|ERROR|132.925000|SERVER> Unable to get the number of handles. Error: Serial port write error| in :\D\PSNPb\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(631)
|ERROR|132.939000|SERVER> Failed to enable tool ports| in :\D\PSNPb\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(319)
|ERROR|132.940000|SERVER> TrackerDevice: Cannot connect to data source, ConnectInternal failed| in :\D\PSNPb\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1147)

Thanks in advance!

**Comment by tggadda** [comment] 2021-02-07 03:38
arciasan - I was getting this exact error you're showing and it was because my computer didn't have Bonjour working so it couldn't resolve the P9-12345 style address that NDI Tracker was showing.  I resolved it on Friday by using a packet sniffer (wireshark) to see what IP address NDI tracker was contacting, and then I used that as the NetworkHostname.  My understanding though is that the IP address of the Vega can change so I probably better figure out how to get bonjour working on my computer.

**Comment by adamrankin** [comment] 2021-02-08 01:16
The IP settings can be enabled and configured using the Configure tool provided in the NDI toolbox.

**Closed** 2021-03-19 18:10 UTC

**Comment by Yunxiao-li** [comment] 2022-01-14 08:12
I have the same problems, could you solve the problem?

**Comment by Yunxiao-li** [comment] 2022-01-19 09:03
I have solve the problem and find the reason.
If IP is dynamic, NetworkHostname using Bonjour name.
If IP is static, NetworkHostname using IP address from the tooltip on the connection as follow:
![image](https://user-images.githubusercontent.com/69031786/150098106-9b1e383e-d501-4347-a47e-994a428a27a4.png)

**Comment by yunmengzhang** [comment] 2023-03-09 11:29
> I have solve the problem and find the reason. If IP is dynamic, NetworkHostname using Bonjour name. If IP is static, NetworkHostname using IP address from the tooltip on the connection as follow: ![image](https://user-images.githubusercontent.com/69031786/150098106-9b1e383e-d501-4347-a47e-994a428a27a4.png)

Could you tell me how to connect the polaris vega and host computer? I didn't find polaris vega in ToolBox.

**Comment by ningw-git** [comment] 2024-08-08 12:41
Have you solved your problem? I encountered the same problem in 2024. I solved the NetworkHostname and NetworkPort problems, but the following error still occurred:
|INFO|000.032000| Software version: Plus-2.8.0.62873a16 - Win64| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(122)
|INFO|000.032000| Logging at level 3 to file: D:/PlusServer/install/PlusApp-2.8.0.20191105-Win64/data/080824_194208_PlusLog.txt| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(123) |INFO|000.379000| -2.8.0) - Epiphan (ver: Plus-2.8.0) - FakeTracker (ver: Plus-2.8.0) - GenericSerialDevice (ver: Plus-2.8.0) - ICCapturing (ver: The Imaging Source UDSHL-3.4) - ImageProcessor (ver: Plus-2.8.0) - IntelRealSense (ver: Plus-2.8.0) - Microchip (ver: Plus-2.8.0) - MmfVideo (ver: Plus-2.8.0) - NDITracker (ver: NDICAPI-1.7) - NoiseVideo (ver: Plus-2.8.0) - OpenCVVideo (ver: Plus-2.8.0) - OpenIGTLinkTracker (ver: OpenIGTLink v3.1.0) - OpenIGTLinkVideo (ver: OpenIGTLink v3.1.0) - OptiTrack (ver: Plus-2 .8.0) - OpticalMarkerTracker (ver: Plus-2.8.0) - PhidgetSpatial (ver: Plus-2.8.0) - PolarisTracker (ver: NDICAPI-1.7) - SavedDataSource (ver: Plus-2.8.0) - UsSimulator (ver: Plus-2.8.0) - VFWVideo (ver: Plus-2.8.0) - VirtualBufferedCapture (ver: Plus-2.8.0) - VirtualCapture (ver: Plus-2.8.0) - VirtualDiscCapture (ver: Plus-2.8.0) - VirtualMixer (ver: Plus-2.8.0) - VirtualSwitcher (ver: Plus-2.8.0) - VirtualTextRecognizer (ver: Plus-2.8.0) - VirtualVolumeReconstructor (ver: Plus-2.8.0) - WitMotionTracker (ver: Plus-2. 8.0) | in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(127) |INFO|000.382000| Server host name: PC-20221110SWJT| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(158) |INFO|000.387000| Server IP addresses: 169.254.216.10, 169.254.189.249, 192.168.2.94, 127.0.0.1| in E:\D \PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(178) |INFO|000.387000| Start remote control server at port: 18904| using configuration file: D:\PlusServer\install\PlusApp-2.8.0.20191105-Win64\config\PlusDeviceSet_Server_NDIVega.xml| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(639) |INFO|153.505000| Server process command line: "D:/PlusServ er/install/PlusApp-2.8.0.20191105-Win64/bin/PlusServer.exe" --config-file="PlusDeviceSet_Server_NDIVega.xml" --verbose=3| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(320) |INFO|154.167000| Server process started successfully| E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(329) |ERROR|244.895000|SERVER> Unable to open OpenCV video device.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\OpenCVVideo\vtkPlusOpenCVCaptureVideoSource.cxx(193) |ERROR|244.908000|SERVER> VideoDevice: Cannot connect to data source, ConnectInternal failed| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1147) |ERROR|244.908000|SERVER> Unable to connect device: VideoDevice.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(353) |ERROR|244.998000|SERVER> Host not capable of given communications parameters| 4.998000|SERVER> Datacollector failed to connect to devices| in :\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106) |INFO|245.070000|SERVER> warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:808) |INFO|245.071000|SERVER> warning: rtsp://192.168.0.30/video (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:809) |ERROR|245.078000| Server stopped unexpectedly. Return code: 1| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(864) |INFO|245.079000| Disconnect request successful|

**Comment by Sunderlandkyl** [comment] 2024-08-08 13:38
@ningw-git Your config file is unable to connect to an OpenCV video device that is looking for an rtsp connection. Do you have a camera that you are trying to connect to?

**Comment by ningw-git** [comment] 2024-08-08 13:58
> @ningw-git Your config file is unable to connect to an OpenCV video device that is looking for an rtsp connection. Do you have a camera that you are trying to connect to?

@Sunderlandkyl 
Hi, first of all thank you very much for your answer, I think the above problem is because I have the wrong .xml file. I loaded the minimalist .xml file after seeing the problem in the forum. I want to connect NDI Polaris Vega ST to PlusServer and 3D Slicer, but now I keep getting errors when connecting NDI Polaris Vega ST to PlusServer. I have read various forums, but the problem keeps occurring:
|INFO|1644.036000| Connect using configuration file: D:\PlusServer\install\PlusApp-2.8.0.20191105-Win64\config\PlusDeviceSet_Server_NDIVega.xml| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(639)
|INFO|1644.036000| Server process command line: "D:/PlusServer/install/PlusApp-2.8.0.20191105-Win64/bin/PlusServer.exe" --config-file="PlusDeviceSet_Server_NDIVega.xml" --verbose=3| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(320) |INFO|1644.699000| Server process started successfully| 6000|SERVER> Unable to get the number of handles. Error: Serial port write error| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(631) |ERROR|1667.477000|SERVER> Failed to enable tool ports| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(319) |ERROR|1667.477000|SERVER> TrackerDevice: Cannot connect to data source, ConnectInternal failed| 47) |ERROR|1667.477000|SERVER> Unable to connect device: TrackerDevice.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(353) |ERROR|1667.478000|SERVER> Datacollector failed to connect to devices| in :\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106) |ERROR|1667.550000| Server stopped unexpectedly. Return code: 1| 0| Disconnect request successful| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(632)
[PlusDeviceSet_Server_NDIVega_mini.txt](https://github.com/user-attachments/files/16549080/PlusDeviceSet_Server_NDIVega_mini.txt)
As a beginner, I really want to solve it, but I am not strong enough. I am very grateful to all the professionals on the platform.

**Comment by ningw-git** [comment] 2024-08-08 14:12
Hi, first of all thank you very much for your answer, I think the above problem is because I have the wrong .xml file. I loaded the minimalist .xml file after seeing the problem in the forum. I want to connect NDI Polaris Vega ST to PlusServer and 3D Slicer, but now I keep getting errors when connecting NDI Polaris Vega ST to PlusServer. I have read various forums, but the problem keeps occurring:
|INFO|1644.036000| Connect using configuration file: D:\PlusServer\install\PlusApp-2.8.0.20191105-Win64\config\PlusDeviceSet_Server_NDIVega.xml| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(639)
|INFO|1644.036000| Server process command line: "D:/PlusServer/install/PlusApp-2.8.0.20191105-Win64/bin/PlusServer.exe" --config-file="PlusDeviceSet_Server_NDIVega.xml" --verbose=3| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(320) |INFO|1644.699000| Server process started successfully| 6000|SERVER&gt; Unable to get the number of handles. Error: Serial port write error| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(631) |ERROR|1667.477000|SERVER&gt; Failed to enable tool ports| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(319) |ERROR|1667.477000|SERVER&gt; TrackerDevice: Cannot connect to data source, ConnectInternal failed| 47) |ERROR|1667.477000|SERVER&gt; Unable to connect device: TrackerDevice.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(353) |ERROR|1667.478000|SERVER&gt; Datacollector failed to connect to devices| in :\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106) |ERROR|1667.550000| Server stopped unexpectedly. Return code: 1| 0| Disconnect request successful| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(632)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PlusToolkit/PlusLib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月8日(星期四) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PlusToolkit/PlusLib] Cannot connect to NDI Polaris Vega with Plus Server Launcher (#519)





 
@ningw-git Your config file is unable to connect to an OpenCV video device that is looking for an rtsp connection. Do you have a camera that you are trying to connect to?

**Comment by Sunderlandkyl** [comment] 2024-08-08 19:47
@ningw-git Can you connect to the Vega using the NDI Toolbox?

**Comment by ningw-git** [comment] 2024-08-09 02:14
Thank you very much for your reply. First, I checked that the three NDI ToolBox (NDI Configure/NDI Track/ NDI Capture) are all connected normally. I will attach the picture. Then I also attached the picture of our device (NDI Polaris Vega ST and probe). We used a C++ sample program before to connect to this device. I also attached the picture.
1. Now we want to connect this device through 3D slicer, so I learned about the OpenIGTLink plug-in in slicer. My first question is: Can I use this plug-in directly to connect to our device?
2. I checked the information and found that the slicer plug-in uses the OpenIGTLink protocol, but the NDI device does not support this protocol. You must use the Plus Server software as an intermediate layer to connect to the NDI device, and then you can use the slicer plug-in to establish a connection with the Plus Server? Is this statement correct? This is my second question.
3. Yesterday I tried to connect to the NDI device using Plus Server. I used two .xml files to try to connect, but it kept failing, and the two configuration files had the same output errors (these two files: PlusDeviceSet_Server_NDIPolaris.xml/PlusDeviceSet_Server_NDIVega.xml). I attached the two files and the output errors again. In the comments, I saw that the minimalist version of .xml (without adding device) was used, but the error was still the same.
Finally, thank you for your answer. The above are all my questions this time. If you can reply, I will be very grateful.
![NDI_Configure](https://github.com/user-attachments/assets/08903468-34a5-4a71-bebb-0df80940d4e6)
![NDI_ToolBox](https://github.com/user-attachments/assets/2500c362-b38c-46e8-aba0-c0298f0f45f6)
![NDI_Tracker](https://github.com/user-attachments/assets/90783478-7d1e-4ad3-ae8a-df8de2acd9f1)
![our_c++sample_connect_successful](https://github.com/user-attachments/assets/4293ead9-3e2f-4338-b7e5-f1e32b55b2af)
![our_ndi_device](https://github.com/user-attachments/assets/43793cf0-5dcb-4865-82ed-6a84483c9c61)
[PlusDeviceSet_Server_NDIPolaris.txt](https://github.com/user-attachments/files/16555076/PlusDeviceSet_Server_NDIPolaris.txt)
[PlusDeviceSet_Server_NDIPolaris_ERROR.txt](https://github.com/user-attachments/files/16555077/PlusDeviceSet_Server_NDIPolaris_ERROR.txt)
[PlusDeviceSet_Server_NDIVega.txt](https://github.com/user-attachments/files/16555078/PlusDeviceSet_Server_NDIVega.txt)

**Comment by ningw-git** [comment] 2024-08-09 04:22
> I have solve the problem and find the reason. If IP is dynamic, NetworkHostname using Bonjour name. If IP is static, NetworkHostname using IP address from the tooltip on the connection as follow: ![image](https://user-images.githubusercontent.com/69031786/150098106-9b1e383e-d501-4347-a47e-994a428a27a4.png)

Hello, how did you solve this problem? Can you send me the configuration file? Is the IP you mentioned dynamic or static? How can I check it?

**Comment by ningw-git** [comment] 2024-08-09 10:24
@Sunderlandkyl 
Can you help me? I'm really anxious, thank you very much
