### ISSUE TITLE
PlusServer CPU usage doubles after activating OpenIGTLink connections in Slicer

### ISSUE THREAD

**Issue by cpinter** [PlusToolkit/PlusLib#698] opened 2020-06-17 15:46 UTC
Please see this video:
https://1drv.ms/u/s!Ao_a-dPPX98ZhK5N32ny6O1bEHOYqA?e=SyPdTO

We have three video streams. The depth and RGB images from RealSense, and the lower resolution video from a thermal camera. With all three connections inactive, PlusServer's CPU usage is 21%. After activating the connections one by one, CPU usage keeps increasing until 42%. When we deactivate them again, CPU usage returns to the original level.

The question is why does the PlusServer CPU usage increase when I activate the IGT connections in Slicer? Is there a way to prevent this? Thanks!

**Comment by lassoan** [comment] 2020-06-17 16:26
PlusServer does more work (sends data), so its CPU usage is expected to increase.

Do you mean PlusServerLauncher CPU usage increase is unexpected? It may be because it forwards PlusServer log messages to Slicer.

**Comment by adamrankin** [comment] 2020-06-17 16:33
Yes, Plus server doesn't do any image manipulation work unless it has someone to send to.

Building a debug build now. I don't have a RealSense but I can try with two webcam devices.

**Comment by cpinter** [comment] 2020-06-17 17:20
I see, this is useful information, thank you!

Based on the exact duplication of the percentage it was suspicious that it does something twice when the connections are active, but apparently it is a coincidence.

Is there a simple way to turn off log forwarding? It might be worth a try. On a medium strength laptop sending these three video streams are enough to max out the CPU, and even showing the data in Slicer is sluggish.

I let @carlos-luque chime in as well. I took the video so I created the ticket, but he knows more about the project and the actual problem.

**Comment by carlos-luque** [comment] 2020-06-18 15:23
Hello, 
   The information is useful. 

I deeply checked the CPU utilization of Slicer and Plus and generating several videos in different folders (uploaded in this [](https://drive.google.com/drive/folders/1EtFtkj6-7QfNQ9FcX9RSAqWOC4IIy326)). I think this study can be useful. 

The test environment is:
- **Cameras**:
  - Webcam (logitech c922 Pro)
  - RealSense D415
  - Q1, thermal camera
- **Application**
   - Slicer + Plus
       - Slicer version is preview 2020 - 01- 08
       - Plus
           - Latest  release version
           - My built version
               - Real Sense SDK version: 2.35.2
               - Q1 SDK
   - FCal
   - Intel RealSense Viewer
 - **Plus Devices**:
    - Real Sense
    - Infrared Q1
    - Microsoft Media Foundation compatible imaging device for Webcam
 - **Image resolution**:
     - 1024x720 (RealSense and WebCam camera)
     -  640x480 (RealSense and WebCam camera) 
     -  380x288 (Q1 camera)

My conclusions:
- When the camera Realsene is used:
   - Fcal has similar CPU utilization (around 20%) to Plus Server (both version) without IGTL connection from Slicer.
   - When the images are captured in Fcal, the CPU usage is around 20 -25 %. 
   - Fcal and Plus Server without IGTL connection from Slicer have the same CPU usage as the Intel Real Sense viewer. 
   - In RealSense Viewer, the CPU utilization is a little higher than Plus without IGTL connection, because the images are shown.
   - When an IGTL connection is opened in Plus Server from Slicer, the CPU usage is unexpected depending on the frame rate.
- When other cameras are used:
  - The CPU usage of Plus Server with an IGTL connection from Slicer is not significant. 

I have a dobut:
- Does Fcal open some IGTL connection to receive the images from Plus Server? If so, there is some difference between Fcal and Slicer client.
- How is an IGTL message created from a device stream? Is there some mutual exclusion between device and IGTL Server?

**Comment by lassoan** [comment] 2020-06-19 13:40
> When an IGTL connection is opened in Plus Server from Slicer, the CPU usage is unexpected depending on the frame rate

What do you mean by "unexpected"? You would expect higher or lower CPU usage than the actual?

> Does Fcal open some IGTL connection to receive the images from Plus Server?

fCal does not start an OpenIGTLink server, so unless you add an OpenIGTLink client(s) to the data sources, no OpenIGTLink connections will be created.

> How is an IGTL message created from a device stream? Is there some mutual exclusion between device and IGTL Server?

Devices write into a circular buffer on background threads and OpenIGTLink server reads from the circular buffer and sends the messages on a different thread. There is minimal blocking (just for the time of copying the data from/to the buffer). However, it may be possible that there are some blocks caused by waiting for IO or hardware internally in the device SDK.

**Comment by carlos-luque** [comment] 2020-06-19 14:43
> > When an IGTL connection is opened in Plus Server from Slicer, the CPU usage is unexpected depending on the frame rate
> 
> What do you mean by "unexpected"? You would expect higher or lower CPU usage than the actual?

I do not expect that a IGTL connection from Slicer client has a significant impact on CPU usage when the RealSense camera is set up in Plus. 
I compared the CPU usage in other cameras (Webcam or thermal camera), IGTL connections do not increase the CPU usage.
I would like to know the reason why an IGTL connection from Slicer increases the CPU usage so much in the Realsense configuration in Plus.  

> > Does Fcal open some IGTL connection to receive the images from Plus Server?
> 
> fCal does not start an OpenIGTLink server, so unless you add an OpenIGTLink client(s) to the data sources, no OpenIGTLink connections will be created.

it´s interesting
> 
> > How is an IGTL message created from a device stream? Is there some mutual exclusion between device and IGTL Server?
> 
> Devices write into a circular buffer on background threads and OpenIGTLink server reads from the circular buffer and sends the messages on a different thread. There is minimal blocking (just for the time of copying the data from/to the buffer). However, it may be possible that there are some blocks caused by waiting for IO or hardware internally in the device SDK.

It´s interesting. Do you know how to check it easily? 

Thanks a lot

**Comment by Sunderlandkyl** [comment] 2020-06-19 15:07
@carlos-luque what RealSense SDK version did you use when building Plus?
If I recall correctly the SDK was poorly optimized in earlier versions, even the example application had high CPU usage.

@markasselin recently updated the SDK in PLTools to 2.33.1, which should have much better performance.

**Comment by adamrankin** [comment] 2020-08-13 17:51
Is this still occurring?

**Comment by cpinter** [comment] 2020-08-14 20:10
As far as I know, yes. But I'm not sure about whether @carlos-luque made progress with this lately.

I suggested checking whether there is any compression involved, and he said he didn't think so. I think it would be good to make sure at least that.

**Comment by adamrankin** [comment] 2020-08-17 16:29
Is this perhaps specific to RealSense? There is an increase when Slicer connects, but for the devices I've tested (webcam, capture card, US) the increase seems as expected.

**Comment by adamrankin** [comment] 2020-08-18 13:27
I've ordered a D435. I'll be able to investigate when it arrives.

**Comment by adamrankin** [comment] 2020-08-24 15:37
Performance profiling with D435i, SDK 2.36.0 build 2034, Slicer nightly 2020-08-15 showed no abnormal behaviour with regards to CPU usage.

On my machine, CPU usage increased from 0% to ~4-7% when either RGB (1280x720@30) or Depth (848x480@30) stream were enabled individually.

Main CPU usage was FlipClipImageGeneric (https://github.com/IGSIO/IGSIO/blob/master/Source/IGSIOCommon/igsioVideoFrame.cxx#L39) as expected.

**Comment by adamrankin** [comment] 2020-08-25 13:38
I'll close this, but if you have a repro case, please feel free to re-open!

**Comment by carlos-luque** [comment] 2020-08-26 12:33
Hello @adamrankin, 
 
I was on holiday. I couldn´t open this issue. 

Setup: SDK 2.35.2, Slicer nightly 08-01-2020

I have different behaviours than yours. I set up the Realsense camera with a stream enabled in each execution:

- Depth (1280x720@30): CPU usage is 6%. When an OpenIGTLink connection is activated, the CPU usage is 13%.
- RGB(1280x720@30): CPU usage is 8%.  When an OpenIGTLink connection is activated, the CPU usage is 18%.

When both streams are enabled and AlignDepthStream is active:

- The CPU usage is 16%. 
- When two OpenIGTLink connections are activated, the CPU utilization is 37%. 
   - If  an OpenIGTLink connection for the RGB stream is only activated, the CPU utilization is 26%.
   - If an OpenIGTLink connection for the Depth stream is only activated, the CPU usage is 23 %. 

I don´t expect that the CPU utilization is increased pretty much when the OpenIGTLink connections are active

I will build Plus with new SDK and use the Slicer nightly these days to check if I have other behaviours.

**Comment by adamrankin** [comment] 2020-08-26 16:37
The CPU will definitely increase when the IGT link connection is made active. Plus has a number of optimizations to not do work if no one is requesting data.

I will profile those configurations and report back.

**Comment by carlos-luque** [comment] 2020-08-27 13:31
Hello @adamrankin 

  I agree with you about the CPU usage will increase when an IGT link connection is active. However, I expect that the CPU usage of a IGTL link connector is below 5%. Currently, the  CPU utilization increase is 10-20 % 

I did several profilings:

- The function crc64 of OpenIGTLink is invoked 100 % time when two IGT link connections are activated in Realsense camera
- The CPU usage of Webcam (device MMF 1024x720) is 2% and when an IGT link conections is activated, it is 6%.

**Comment by adamrankin** [comment] 2020-08-27 19:15
Profiling shows me that everything is normal. I've added a pull request to OpenIGTLink to make crc64 calculation optional, but other than that there is no abnormal CPU usage. The jump in CPU usage is normal and expected.

**Comment by adamrankin** [comment] 2020-08-27 19:16
If you really need to remove CPU usage, you can identify the native orientation of your webcam, and adjust the orientation in your Plus config file accordingly, to remove any CPU usage from FlipClipImage (rotating the image to match desired orientation).

**Comment by carlos-luque** [comment] 2020-08-28 12:44
Hello @adamrankin, 

   I changed the orientation (MF) in each stream and the fucntion FlipClipImage was not invoked. The CPU usage was discreased in 3-4%, but the CPU usage was the same as previous when an IGT Link connector was activated (10 -20 % CPU usage). The function FlipClipImage sligthly affects in this case (3-4% CPU). 

I analysied the function vtkPlusOpenIGTLinkServer::SendLatestFramesToClients:

- The variable trackedFrameList->GetNumberOfTrackedFrames() was always 1. 
- The processing time (send tracked frame) is 55 ms in average.

I´d like to know your configuration to not have effect of the IGTL link connectors in CPU usage. I am using the default configuration file for the Realsense camera with PortUsImageOrientation "MF", frame size 1280 x 720 and frame rate  30. 
 
Could you give some hints to analysis my abnormal CPU usage in the RealSense camera when some IGT link connector is active?

Thanks for your time

**Comment by adamrankin** [comment] 2020-09-02 19:06
`I´d like to know your configuration to not have effect of the IGTL link connectors in CPU usage.`

I think perhaps there's a bit of miscommunication. I'm not saying there's no increase. I'm saying the increase is expected because Plus doesn't do any work unless it has too. When the IGT link connection is activated in Slicer, it makes a connection to Plus server and so it starts to do work. This is where the increase in CPU comes from.

After profiling it, the CPU usage that I'm seeing is expected. I don't think it's possible to optimize much more than how it is now. I've added the optional crc64 calculation in OpenIGTLink, but that's about it (and not always a good optimization, if over a bad connection).

**Comment by lassoan** [comment] 2020-09-03 23:22
CPU consumption depends on a lot of things, not just on image resolution. For example, RealSense resamples the depth image in the optical image coordinate system (or vice versa), which is a very costly operation. But there are other things a webcam driver can do, such as automatic gain control, auto-focus, compression/decompression, noise reduction, etc. which can all consume significant CPU time.

**Comment by carlos-luque** [comment] 2020-09-09 08:39
Hello @lassoan, 
 
I agree with you about that, but we're discussing the CPU consumption of the IGT Link connections in Plus Server.

I studied deeply this issue and I used the RealSense camera in the device: IntelRealSense with several image resolutions: 
- 640x480, called Resolution480,
- 1280x720, called Resolution720
- 1920x1080, called Resolution1080

The configuration of the device IntelRealSense was the following:
-	A stream: RGB camera
-	Frame rate: 30
-	No alignment
-	No colorized 
-	Orientation: MF

In this camera configuration, SDK does not do extra work. 

The Plus version used are: 
 - Release: 2.8 release, 
- nightly 
- my built version. 

The results are the same as all Plus versions and they are summarized in the below table: 

Device| Resolution | No IGT link connector (CPU percent) | Yes IGT link Connector (CPU percent)|
| ------------- | ------------- |  :---: | :---: |
IntelRealSense | Resolution1080 | 4.5 % | 21 % |
IntelRealSense | Resolution720 | 2.5 % | 10 % |
IntelRealSense | Resolution480 | 1.0 % | 3.0 % |

I observe that the increase of the CPU utilization is proportional to the image resolution when an IGT Link connecter is made active. For example, the increase of CPU utilization in the Resolution720 is around three times the CPU utilization of the Resolution480 as the image size of the Resolution720 is around three times the image size of the Resolution480. It is same as the Resolution1080. 

I guess that _the issue_ is the two copies of a frame when the frame is sent. 

The _first copy_ is that the moving a frame from buffer to channel and the invocation stack is

| Function | Module |
| ------------- | ------------- |
| memcmp |  |
| …. | … |
| igsioVideoFrame::operator= |	vtkIGSIOCommon |
| StreamBufferItem::operator= | vtkPlusDataCollection |	
| StreamBufferItem::DeepCopy | vtkPlusDataCollection |	
| vtkPlusBuffer::GetStreamBufferItem | vtkPlusDataCollection |	
| vtkPlusChannel::GetTrackedFrame |	vtkPlusDataCollection |	
| vtkPlusChannel::GetTrackedFrameList | vtkPlusDataCollection |	
|vtkPlusOpenIGTLinkServer::SendLatestFramesToClients | vtkPlusServer |
| vtkPlusOpenIGTLinkServer::DataSenderThread |  vtkPlusServer |

The _second copy_ is that the creation of a variable  igsioVideoFrame from a StreamBufferItem, and the invocation stack is

| Function | Module |
| ------------- | ------------- |
| malloc |  |
| …. | … |
| igsioVideoFrame::operator= |	vtkIGSIOCommon |
| igsioVideoFrame::igsioVideoFrame |	vtkIGSIOCommon |	
| vtkPlusChannel::GetTrackedFrame |	vtkPlusDataCollection |	
| vtkPlusChannel::GetTrackedFrameList | vtkPlusDataCollection |	
|vtkPlusOpenIGTLinkServer::SendLatestFramesToClients | vtkPlusServer |
| vtkPlusOpenIGTLinkServer::DataSenderThread |  vtkPlusServer |

These copies consume a large proportion of the processor in big image sizes such as Resolution720 (921600 pixels times three channels), and Resolution1080 (2073600 pixels times three channels). However, if the image size is small (around 307200 pixels times three channels, Resolution480), the CPU consumption is not significant.  What is the reason to create two copies of a frame when the frame is sent in IGT Link protocol?

Thanks in advance

**Comment by adamrankin** [comment] 2020-09-09 13:12
Ah, outstanding work. I'll investigate to see if we can improve it.

There reason for two copies is simply the current design.

**Comment by lassoan** [comment] 2021-02-03 00:24
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!

**Closed by lassoan** 2021-02-03 00:24 UTC
Labels: PlusLib-PlusServer
