### ISSUE TITLE
how to use calibration result in PLUS config files

### ISSUE THREAD

**Issue by salimohamadi** [PlusToolkit/PlusLib#380] opened 2018-07-11 10:46 UTC
Hi,
I have done the calibration steps in fcal and a .xml file has been generated including a lot of information. I would like to know if all the information should be copied in the config file in PLUS application? if not which parts should be copied?
I have attached my fcal result ( and also the config that should be loaded in PLUS  before calibration )
[fcalConfiguration.docx](https://github.com/PlusToolkit/PlusLib/files/2184092/fcalConfiguration.docx)
[PlusConfigurationFile.docx](https://github.com/PlusToolkit/PlusLib/files/2184093/PlusConfigurationFile.docx)

Thanks
Samaneh Alimohamadi

**Comment by Sunderlandkyl** [comment] 2018-07-11 14:12
Duplicate of #379

**Closed by Sunderlandkyl** 2018-07-11 14:12 UTC
