### ISSUE TITLE
PlusBuild PlusServer tests failure

### ISSUE THREAD

**Issue by kenavolic** [PlusToolkit/PlusLib#966] opened 2022-07-04 09:25 UTC
Since 2022/07/02, our custom build of Plus fails due to PlusServerTest failure. This seems to be the same on Plus dashboard (http://perkdata.cs.queensu.ca/CDash/testSummary.php?project=12&name=PlusServer&date=2022-07-04)?

We are investigating the issue. At first sight, it could come from OpenIGTLink update that seems to be sync with the issue.

EDIT: Building Plus with OpenIGTLink commit 3a2297d173d20596f53d5b5c84600ed4fa51c07c fixes the issue. Thus it comes from the PR about metadata header size validation. Help welcome to know if the problem comes from OpenIGTLink PR or Plus.

**Comment by Sunderlandkyl** [comment] 2022-07-04 17:56
Yeah it was caused by the OpenIGTLink update. Should be fixed with https://github.com/openigtlink/OpenIGTLink/pull/253.

**Closed** 2022-07-05 16:50 UTC
