### ISSUE TITLE
Issue: images were not sending via OpenIGTLink.

### ISSUE THREAD

**Issue by nehk018** [PlusToolkit/PlusLib#301] opened 2017-12-19 13:54 UTC
Hello,
when I run the Plus Server I have the next warning: 

`EmbeddedTransformToFrame attribute of ImageNames/Image element #0 is missing. This element will be ignored.| in /PlusLib/src/PlusOpenIGTLink/PlusIgtlClientInfo.cxx(131)`

I checked in the log that images were not sended 

`Data sent by default: IGTL version: 1Message types: IMAGE. TDATARequested: FALSE. LastTDATASentTimeStamp: -1. TDATAResolution: 0. . Transforms: (none). Strings: (none). Images: (none)`

My PlusOpenIGTLinkServer configuration was:
`
<CoordinateDefinitions>
    <Transform From="Image" To="Reference"
      Matrix="
        1 0 0 0
        0 1 0 0
        0 0 1 0
        0 0 0 1" />
  </CoordinateDefinitions>
  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="VideoStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Reference" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
`

Could anyone help me?

**Comment by Sunderlandkyl** [comment] 2017-12-19 14:14
Are you running the most recent version?
There is currently a problem with the PlusServer that is causing some of the tests to fail:  ([PlusServer](http://perkdata.cs.queensu.ca/CDash/testSummary.php?project=12&name=PlusServer&date=2017-12-19) [vtkOpenIGTLinkTrackerTest](http://perkdata.cs.queensu.ca/CDash/testSummary.php?project=12&name=vtkOpenIGTLinkTrackerTest&date=2017-12-19))

From what I can see, the configuration looks fine. Try using the stable release and see if that works: http://perk-software.cs.queensu.ca/plus/packages/stable/

**Comment by Sunderlandkyl** [comment] 2017-12-19 15:02
If the issue that you encountered is related to the one that caused the tests to fail, then I believe that it should be fixed in the next nightly version tomorrow morning.

Let me know if it's fixed, or if you still encounter this problem.

**Comment by adamrankin** [comment] 2017-12-19 15:58
That's my fault. Didn't run tests before merging. Fixing it now.

**Comment by adamrankin** [comment] 2017-12-19 15:59
Oh, Kyle already fixed it. Thanks, sorry!

**Comment by carlos-luque** [comment] 2017-12-19 20:23
@Sunderlandkyl  Thanks for your reply. This fix works.  We're using the nightly code version  in Linux because we cannot use the stable version (PLus-2.6). The reason is due we have some compilation errors:

`Plus-26/PlusBuild-bin26/PlusLib/src/PlusServer/vtkPlusOpenIGTLinkServer.cxx:785:9: error: ‘MessageContent’ is not a member of ‘igtlio::PolyDataConverter’
         igtlio::PolyDataConverter::MessageContent content;
         ^
Plus-26/PlusBuild-bin26/PlusLib/src/PlusServer/vtkPlusOpenIGTLinkServer.cxx:786:9: error: ‘content’ was not declared in this scope
         content.deviceName = "PlusServer";
         ^
/Plus-26/PlusBuild-bin26/PlusLib/src/PlusServer/vtkPlusOpenIGTLinkServer.cxx:788:9: error: ‘VTKToIGTL’ is not a member of ‘igtlio::PolyDataConverter’
         igtlio::PolyDataConverter::VTKToIGTL(content, (igtl::PolyDataMessage::Pointer*)&msg);
`
We have those errors in the PlusBuild versions: Plus-2.6 and master

Our environment setup is:

- PlusBuild version: Plus-2.6 and master
- PlusLib version: Plus-2.6 It is set via  the variable in PlusBuild
- PlusApp version: Plus-2.6. It is set via the variable in PlusBuild
- gcc 5.4.0
- cmake 3.5.1
- Qt5 version installed via package
- Ubuntu 16.04

Have you had those errors in the version Plus-2.6 before?

**Comment by Sunderlandkyl** [comment] 2017-12-19 20:49
Ah, I didn't know you were using Linux, and compiling your own version of Plus.

Yes, it's caused by compiling with a different version of OpenIGTLinkIO.

These lines show the specific commit of OpenIGTLinkIO that should be used for the Plus-2.6 branch: https://github.com/PlusToolkit/PlusBuild/blob/5c2d4417f407ad2a974c6b21817a673f406eccd8/SuperBuild/External_OpenIGTLinkIO.cmake#L32-L33 
The master branch generally just uses the latest version for all dependencies.

The specific commits used for dependencies in Plus-2.6 can be seen [here](https://github.com/PlusToolkit/PlusBuild/commit/5c2d4417f407ad2a974c6b21817a673f406eccd8).

**Comment by carlos-luque** [comment] 2017-12-20 08:45
Hello, 

   We managed to compile the Plus version 2.6. Thanks a lot.

Now if we run PlusServerLauncher, it cannot run PlusServer because the PlusServer path is not right.  I'm copying the errors:

`Start remote control server at port: 18904
Connect using configuration file: Plus-26/PlusBuild-bin26/PlusLibData/Server_OpenCVVideoSource_Webcam.xml
Server process command line: "/Plus-26/PlusBuild-bin26/bin/PlusServerLauncherPlusToolkit/Plus-26/PlusBuild-bin26/PlusLib/src/PlusCommon/vtkPlusAccurateTimer.cxx(54)
/PlusServer" --config-file="/Plus-26/PlusBuild-bin26/PlusLibData/Server_OpenCVVideoSource_Webcam.xml" --verbose=3
|ERROR|031.478017| Server process error: FailedToStart| in /Plus-26/PlusBuild-bin26/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(444)
|ERROR|031.500444| Failed to start server process| in /Plus-26/PlusBuild-bin26/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(219)
`

We think the issue is that the PlusServer path does not have a period "." : **.**/PlusServer" --config-file="/Plus-26/PlusBuild-bin26/PlusLibData/Server_OpenCVVideoSource_Webcam.xml" --verbose=3
 
We can run PlusServer via command line and it works.

**Comment by Sunderlandkyl** [comment] 2017-12-20 16:31
If I'm reading the code correctly, the executable for PlusServer should be retrieved as an absolute, instead of a relative one
([PlusServerLauncherMainWindow::StartServer()](https://github.com/PlusToolkit/PlusApp/blob/b3f1731f4ae3ed1490da5c99beaa5fc6fe2a4b3e/PlusServerLauncher/PlusServerLauncherMainWindow.cxx#L192)->
[vtkPlusConfig::GetPlusExecutablePath()](https://github.com/PlusToolkit/PlusLib/blob/d6cf2463c624a7f9a65eb92ad6f9a914f3f03bd3/src/PlusCommon/vtkPlusConfig.cxx#L1034-L1042)->
[vtkPlusConfig::GetAbsolutePath()](https://github.com/PlusToolkit/PlusLib/blob/d6cf2463c624a7f9a65eb92ad6f9a914f3f03bd3/src/PlusCommon/vtkPlusConfig.cxx#L950-L967))

It could be that there's some issue in getting the correct path on Linux, I'll look into it. Thanks for letting me know!

**Comment by Sunderlandkyl** [comment] 2018-01-15 18:48
Remaining issue moved to #316.

**Closed by Sunderlandkyl** 2018-01-15 18:48 UTC
