### ISSUE TITLE
How to Use Intel realsense sr300 as pose tracking devices?

### ISSUE THREAD

**Issue by yayali98** [PlusToolkit/PlusLib#322] opened 2018-01-23 01:58 UTC
I try to use sr300 geting  tracked data ,but I used Plus Server Lanuch ，it appeared this error:connection failed
|INFO|000.090000| Software version: Plus-2.6.0.268f9604 - Win64| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(102)
|INFO|000.090000| Logging at level 3 to file: D:/toolsoftware/Plus/PlusApp-2.6.0.20171129-Win64/data/012318_094358_PlusLog.txt| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(103)
|INFO|000.092000| Supported devices: - 3dConnexion (ver: Plus-2.6.0) - AuroraTracker (ver: NDICAPI-1.7) - ChRobotics (ver: Plus-2.6.0) - Epiphan (ver: Plus-2.6.0) - FakeTracker (ver: Plus-2.6.0) - GenericSerialDevice (ver: Plus-2.6.0) - ICCapturing (ver: The Imaging Source UDSHL-3.4) - ImageProcessor (ver: Plus-2.6.0) - Microchip (ver: Plus-2.6.0) - MmfVideo (ver: Plus-2.6.0) - NDITracker (ver: NDICAPI-1.7) - NoiseVideo (ver: Plus-2.6.0) - OpenIGTLinkTracker (ver: OpenIGTLink v3.1.0) - OpenIGTLinkVideo (ver: OpenIGTLink v3.1.0) - OptiTrack (ver: Plus-2.6.0) - OpticalMarkerTracker (ver: Plus-2.6.0) - PhidgetSpatial (ver: Plus-2.6.0) - PolarisTracker (ver: NDICAPI-1.7) - SavedDataSource (ver: Plus-2.6.0) - UsSimulator (ver: Plus-2.6.0) - VFWVideo (ver: Plus-2.6.0) - VirtualBufferedCapture (ver: Plus-2.6.0) - VirtualCapture (ver: Plus-2.6.0) - VirtualDiscCapture (ver: Plus-2.6.0) - VirtualMixer (ver: Plus-2.6.0) - VirtualSwitcher (ver: Plus-2.6.0) - VirtualVolumeReconstructor (ver: Plus-2.6.0) | in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(107)
|INFO|000.098000| Server host name: DESKTOP-FO5R8PM| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(127)
|INFO|000.113000| Server IP addresses: 10.10.10.206, 192.168.89.1, 192.168.146.1, 127.0.0.1| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(147)
|INFO|000.114000| Start remote control server at port: 18904| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(156)
|INFO|005.026000| Connect using configuration file: D:\Data\PlusLibData-master\ConfigFiles\PlusDeviceSet_Server_IntelRealSenseTracker.xml| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(314)
|INFO|005.027000| Server process command line: "D:/toolsoftware/Plus/PlusApp-2.6.0.20171129-Win64/bin/PlusServer.exe" --config-file="D:\Data\PlusLibData-master\ConfigFiles\PlusDeviceSet_Server_IntelRealSenseTracker.xml" --verbose=3| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(205)
|INFO|005.185000|SERVER> System start timestamp: 318715
|INFO|005.185000|SERVER> Software version: Plus-2.6.0.268f9604 - Win64
|INFO|005.185000|SERVER> Logging at level 3 (INFO) to file: D:/toolsoftware/Plus/PlusApp-2.6.0.20171129-Win64/data/012318_094403_PlusLog.txt
|INFO|005.185000|SERVER> Server status: Reading configuration.
|ERROR|005.185000|SERVER> Unknown device type: IntelRealSenseTracker. Supported devices: 3dConnexion, AuroraTracker, ChRobotics, Epiphan, FakeTracker, GenericSerialDevice, ICCapturing, ImageProcessor, Microchip, MmfVideo, NDITracker, NoiseVideo, OpenIGTLinkTracker, OpenIGTLinkVideo, OptiTrack, OpticalMarkerTracker, PhidgetSpatial, PolarisTracker, SavedDataSource, UsSimulator, VFWVideo, VirtualBufferedCapture, VirtualCapture, VirtualDiscCapture, VirtualMixer, VirtualSwitcher, VirtualVolumeReconstructor| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDeviceFactory.cxx(386)
|WARNING|005.206000|SERVER> No output channels defined. Unable to locate any for data collection.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(161)
|ERROR|005.206000|SERVER> Datacollector failed to read configuration| in :\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(114)
|INFO|005.206000| Server process terminated.| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(453)
|INFO|005.206000| Disconnect request successful| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(307)
|ERROR|005.207000| Failed to start server process| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(219)
|INFO|824.029000| Connect using configuration file: D:\Data\PlusLibData-master\ConfigFiles\PlusDeviceSet_Server_IntelRealSenseTracker.xml| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(314)

**Comment by Sunderlandkyl** [comment] 2018-01-23 02:10
Support for the Intel Realsense camera is not included in any of the currently available packages.

You can compile a package supporting the Realsense by compiling Plus with the PLUS_USE_INTELREALSENSE cmake flag enabled.

Build instructions (https://github.com/PlusToolkit/PlusBuild/blob/master/README.md)
You'll also need to install the IntelRealSense SDK or runtime.

@lassoan Were there any plans to add Realsense support to any of the packages in the near future?

**Comment by yayali98** [comment] 2018-01-23 02:25
Thank you .I will try .Do you know which tracker device the currently available packages support? @Sunderlandkyl

**Comment by Sunderlandkyl** [comment] 2018-01-23 02:39
You can see the list of devices for the current packages in the table here: https://plustoolkit.github.io/download

You can also see which devices are enabled for the current package in the log that you provided:
> |INFO|000.092000| Supported devices: - 3dConnexion (ver: Plus-2.6.0) - AuroraTracker (ver: NDICAPI-1.7) - ChRobotics (ver: Plus-2.6.0) - Epiphan (ver: Plus-2.6.0) - FakeTracker (ver: Plus-2.6.0) - GenericSerialDevice (ver: Plus-2.6.0) - ICCapturing (ver: The Imaging Source UDSHL-3.4) - ImageProcessor (ver: Plus-2.6.0) - Microchip (ver: Plus-2.6.0) - MmfVideo (ver: Plus-2.6.0) - NDITracker (ver: NDICAPI-1.7) - NoiseVideo (ver: Plus-2.6.0) - OpenIGTLinkTracker (ver: OpenIGTLink v3.1.0) - OpenIGTLinkVideo (ver: OpenIGTLink v3.1.0) - OptiTrack (ver: Plus-2.6.0) - OpticalMarkerTracker (ver: Plus-2.6.0) - PhidgetSpatial (ver: Plus-2.6.0) - PolarisTracker (ver: NDICAPI-1.7) - SavedDataSource (ver: Plus-2.6.0) - UsSimulator (ver: Plus-2.6.0) - VFWVideo (ver: Plus-2.6.0) - VirtualBufferedCapture (ver: Plus-2.6.0) - VirtualCapture (ver: Plus-2.6.0) - VirtualDiscCapture (ver: Plus-2.6.0) - VirtualMixer (ver: Plus-2.6.0) - VirtualSwitcher (ver: Plus-2.6.0) - VirtualVolumeReconstructor (ver: Plus-2.6.0) | in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(107)

and

> |ERROR|005.185000|SERVER> Unknown device type: IntelRealSenseTracker. Supported devices: 3dConnexion, AuroraTracker, ChRobotics, Epiphan, FakeTracker, GenericSerialDevice, ICCapturing, ImageProcessor, Microchip, MmfVideo, NDITracker, NoiseVideo, OpenIGTLinkTracker, OpenIGTLinkVideo, OptiTrack, OpticalMarkerTracker, PhidgetSpatial, PolarisTracker, SavedDataSource, UsSimulator, VFWVideo, VirtualBufferedCapture, VirtualCapture, VirtualDiscCapture, VirtualMixer, VirtualSwitcher, VirtualVolumeReconstructor| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDeviceFactory.cxx(386)

**Comment by yayali98** [comment] 2018-01-23 02:45
I see,thank you agin

**Comment by yayali98** [comment] 2018-01-23 02:45
I see ,thank you agin @Sunderlandkyl

**Comment by lassoan** [comment] 2018-01-23 23:00
> Are there any plans to add Realsense support to any of the packages in the near future?

If the SDK files are small and no driver installation is required then we can add it to packages now. I've added https://github.com/PlusToolkit/PlusLib/issues/325 to track this.

**Comment by Sunderlandkyl** [comment] 2018-01-24 17:21
@yayali98 If you don't need to use the RealSense for surface tracking, you could consider using the OpticalMarkerTracker device instead: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpticalMarkerTracker.html

**Comment by Sunderlandkyl** [comment] 2018-01-25 15:41
@yayali98 RealSense support has now been added to the current stable and nightly packages (#325).

**Comment by Sunderlandkyl** [comment] 2018-02-12 16:40
I'm going to close this issue. If you have any other problems, feel free to reopen this issue or create a new one.

**Closed by Sunderlandkyl** 2018-02-12 16:40 UTC
Labels: question

**Comment by jamesobutler** [comment] 2018-05-30 15:18
I have an SR300 realsense camera and downloaded the latest stable 64bit and 32bit packages with realsense support, but I keep getting an error trying to start PlusServer.  I manually downloaded this [realsense config](https://github.com/PlusToolkit/PlusLibData/blob/6c29c5b72d4e9a6acb90bc43a57cbd3496e894f1/ConfigFiles/PlusDeviceSet_Server_IntelRealSenseTracker.xml) from PlusLibData to use because it wasn't included in the Config directory of the package.  I then noticed that the [IntelRealSenseToolDefinitions](https://github.com/PlusToolkit/PlusLibData/tree/6c29c5b72d4e9a6acb90bc43a57cbd3496e894f1/ConfigFiles/IntelRealSenseToolDefinitions) directory was also missing in the packages Config directory so I added it manually.

When starting PlusServer it keeps failing at "Failed to create an SDK session".  Am I suppose to manually install the SDK as well?  I have Windows 10 version 1803 and Windows recognizes it as the Intel RealSense SR300 Camera since I installed the latest driver 3.3.27.5718 from [here](https://downloadcenter.intel.com/download/25044/Intel-RealSense-Depth-Camera-Manager?product=92329)
```powershell
053018_104648.315|ERROR|000.015000| Failed to create an SDK session| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\IntelRealSense\vtkPlusIntelRealSenseTracker.cxx(459)
053018_104648.319|ERROR|000.020000| TrackerDevice: Cannot connect to data source, ConnectInternal failed| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1204)
053018_104648.325|ERROR|000.026000| Unable to connect device: TrackerDevice.| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(331)
053018_104648.332|ERROR|000.032000| Datacollector failed to connect to devices| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(129)
```

**Comment by lassoan** [comment] 2018-05-30 15:25
SR300 is about 2-3 generations behind the current RealSense cameras. It is also bulky and unreliable (probably due to power or chipset issues it often fails to connect on some computers and does not connect at all on others). I don't think that we support the SR300 anymore, since RealSense SDK dropped support for it. I would recommend to buy a new one, they are incomparably better.

@markasselin Can you confirm if SR300 is not supported anymore by Plus?

**Comment by jamesobutler** [comment] 2018-05-30 15:44
Yeah the SR300 is a couple years old and I think part of the original batch of camera devices (SDK1), but appears to be the only earlier device that is also supported by the newest realsense SDK 2.0 as stated on the [readme](https://github.com/IntelRealSense/librealsense/blob/master/readme.md).

I think realsense in PLUS is currently using SDK1 and hasn't been updated since Feb2017 in PLUS.

Looks like Mark has some updates for SDK1 in his [OMT-RS](https://github.com/markasselin/PlusLib/commits/OMT-RS) branch and maybe some updates to support SDK2 in his [OMT-RS2](https://github.com/markasselin/PlusLib/commits/OMT-RS2) branch?

**Comment by jamesobutler** [comment] 2018-06-22 21:03
@markasselin Checking in again to see if you know if the IntelRealsense camera device is currently working in PLUS master branch with what I believe is SDK1.  Also, the status of your work towards updating the device to use SDK2.0

**Comment by lassoan** [comment] 2018-06-23 03:40
I've seen image and depth camera acquisition and display in Slicer using SDK 2.0. It should be integrated within days.

**Comment by jamesobutler** [comment] 2018-07-30 14:10
I can confirm that the SR300 device now works with the update to use SDK 2.0 and it is now sending its image and depth streams over openigtlink. Thanks!
